module.exports = {make: function (){return( 
[
{"id":"1","eword":"daiwa-roynet-hotel-kyoto-shijo-karasuma","jword":"ダイワロイネットホテル京都四条烏丸","hiragana":"だいわろいやるねっとほてるきょうとしじょうからすま"}
,
{"id":"2","eword":"daiwaroynethotelkyotoshijokarasuma","jword":"ダイワロイネットホテル京都四条烏丸","hiragana":"だいわろいやるねっとほてるきょうとしじょうからすま"}
,
{"id":"3","eword":"kyoto-food-culture-museum-ajiwai-kan","jword":"京の食文化ミュージアムあじわい館","hiragana":"きょうとしょくぶんかみゅーじあむあじわいかん"}
,
{"id":"4","eword":"kyoto-traditional-industry-fureai-kan","jword":"京都伝統産業ふれあい館","hiragana":"きょうとでんとうさんぎょうふれあいかん"}
,
{"id":"5","eword":"mitsui-garden-hotel-kyoto-shijo","jword":"三井ガーデンホテル京都四条","hiragana":"みついがーでんほてるきょうとしじょう"}
,
{"id":"6","eword":"kyoto-international-manga-museum","jword":"京都国際マンガミュージアム","hiragana":"きょうとこくさいまんがみゅーじあむ"}
,
{"id":"7","eword":"kyotomuseumoftraditoinalcrafts","jword":"京都伝統産業ふれあい館","hiragana":"きょうとでんとうさんぎょうふれあいかん"}
,
{"id":"8","eword":"mitsuigardenhotelkyotoshijo","jword":"三井ガーデンホテル京都四条","hiragana":"みついがーでんほてるきょうとしじょう"}
,
{"id":"9","eword":"apahotelkyotoekihorikawadori","jword":"アパホテル京都駅堀川通り","hiragana":"あぱほてるきょうとほりかわとおり"}
,
{"id":"10","eword":"hotel-nikko-princess-kyoto","jword":"ホテル日航プリンセス京都","hiragana":"ほてるにっこうぷりんせすきょうと"}
,
{"id":"11","eword":"shinkansen-central-transfer","jword":"新幹線中央のりかえ口","hiragana":"しんかんせんちゅうおうのりかえぐち"}
,
{"id":"12","eword":"shochiku-kyoto-movie-studio","jword":"松竹京都映画撮影所","hiragana":"しょうちくきょうとえいがさつえいじょ"}
,
{"id":"13","eword":"kyoto-handicraft-center","jword":"京都ハンディクラフトセンター","hiragana":"きょうとはんでぃくらふとせんたー"}
,
{"id":"14","eword":"shinkansenhachijoeastentrance","jword":"新幹線八条東口","hiragana":"しんかんせんはちじょうひがしぐち"}
,
{"id":"15","eword":"kyotoajiwaikan","jword":"京の食文化ミュージアムあじわい館","hiragana":"きょうとしょくぶんかみゅーじあむあじわいかん"}
,
{"id":"16","eword":"apavillahotelkyotoekimae","jword":"アパヴィラホテル京都駅前","hiragana":"あぱゔぃらほてるきょうとえきまえ"}
,
{"id":"17","eword":"shinkansencentraltransfer","jword":"新幹線中央のりかえ口","hiragana":"しんかんせんちゅうおうのりかえぐち"}
,
{"id":"18","eword":"shinkansen-hachijo-east-entrance","jword":"新幹線八条東口","hiragana":"しんかんせんはちじょうぐち"}
,
{"id":"19","eword":"kyotohandicraftcenter","jword":"京都ハンディクラフトセンター","hiragana":"きょうとはんでぃくらふとせんたー"}
,
{"id":"20","eword":"mitsui-garden-hotel","jword":"三井ガーデンホテル京都四条","hiragana":"みついがーでんほてるきょうとしじょう"}
,
{"id":"21","eword":"rihga-royal-hotel-kyoto","jword":"リーガロイヤルホテル京都","hiragana":"りーがろいやるほてるきょうと"}
,
{"id":"22","eword":"kintetsu-railway-central-entrance","jword":"近鉄改札口","hiragana":"きんてつかいさつぐち"}
,
{"id":"23","eword":"kyoto-manga-museum","jword":"京都国際マンガミュージアム","hiragana":"きょうとこくさいまんがみゅーじあむ"}
,
{"id":"24","eword":"mitsuigardenhotel","jword":"三井ガーデンホテル京都四条","hiragana":"みついがーでんほてるきょうとしじょう"}
,
{"id":"25","eword":"kitashirakawa-tenjingu-shrine","jword":"北白川天神宮","hiragana":"きたしらかわてんじんみや"}
,
{"id":"26","eword":"handicraft-center","jword":"京都ハンディクラフトセンター","hiragana":"きょうとはんでぃくらふとせんたー"}
,
{"id":"27","eword":"sumiya-hospitality","jword":"角屋もてなしの文化美術館","hiragana":"すみやもてなしのぶんかびじゅつかん"}
,
{"id":"28","eword":"shinkansen-central-entrance","jword":"新幹線中央口","hiragana":"しんかんせんちゅうおうぐち"}
,
{"id":"29","eword":"kyotomangamuseum","jword":"京都国際マンガミュージアム","hiragana":"きょうとこくさいまんがみゅーじあむ"}
,
{"id":"30","eword":"pontocho-kaburenjo-theater","jword":"先斗町歌舞練場","hiragana":"ぽんとちょうかぶれんじょう"}
,
{"id":"31","eword":"hotel-granvia-kyoto","jword":"ホテルグランヴィア京都","hiragana":"ほてるぐらぐらんゔぃあきょうと"}
,
{"id":"32","eword":"shochikukyotostudio","jword":"松竹京都映画撮影所","hiragana":"しょうちくきょうとえいがさつえいじょ"}
,
{"id":"33","eword":"kansai-airport-limousine-bus","jword":"関空リムジンバス","hiragana":"かんくうりむじんばす"}
,
{"id":"34","eword":"shinkansen-hachijo-entrance","jword":"新幹線八条口","hiragana":"しんかんせんはちじょうぐち"}
,
{"id":"35","eword":"rihgaroyalhotelkyoto","jword":"リーガロイヤルホテル京都","hiragana":"りーがろいやるほてるきょうと"}
,
{"id":"36","eword":"hotel-keihan-kyoto","jword":"ホテル京阪京都グランデ","hiragana":"ほてるけいはんきょうとぐらんで"}
,
{"id":"37","eword":"iwashimizu-hachimangu-shrine","jword":"石清水八幡宮","hiragana":"いわしみずはちまんぐう"}
,
{"id":"38","eword":"kintetsurailwaycentralentrance","jword":"近鉄改札口","hiragana":"きんてつかいさつぐち"}
,
{"id":"39","eword":"universal-studios-japan","jword":"ユニバーサルスタジオジャパン","hiragana":"ゆーえすじぇい"}
,
{"id":"40","eword":"hotelkintetsukyotostation","jword":"ホテル近鉄京都駅","hiragana":"ほてるきんてつきょうと"}
,
{"id":"41","eword":"shinkansenhachijoentrance","jword":"新幹線八条口","hiragana":"しんかんせんはちじょうぐち"}
,
{"id":"42","eword":"toei-kyoto-movie-studio","jword":"東映京都撮影所","hiragana":"とうえいきょうとさつえいじょ"}
,
{"id":"43","eword":"shinkansencentralentrance","jword":"新幹線中央口","hiragana":"しんかんせんちゅうおうぐち"}
,
{"id":"44","eword":"hotelgranviakyoto","jword":"ホテルグランヴィア京都","hiragana":"ほてるぐらぐらんゔぃあきょうと"}
,
{"id":"45","eword":"kyoto-century-hotel","jword":"京都センチュリーホテル","hiragana":"きょうとせんちゅりーほてる"}
,
{"id":"46","eword":"fushimi-inari-taisha-shrine","jword":"伏見稲荷大社","hiragana":"ふしみいなりたいしゃ"}
,
{"id":"47","eword":"rihga-royal-hotel","jword":"リーガロイヤルホテル京都","hiragana":"りーがろいやるほてるきょうと"}
,
{"id":"48","eword":"hotel-mystays-kyoto","jword":"ホテルマイステイズ京都","hiragana":"ほてるまいすていずきょうと"}
,
{"id":"49","eword":"hotelkeihankyoto","jword":"ホテル京阪京都グランデ","hiragana":"ほてるけいはんきょうとぐらんで"}
,
{"id":"50","eword":"apahotelkyotoekimae","jword":"アパホテル京都駅前","hiragana":"あぱほてるきょうとえきまえ"}
,
{"id":"51","eword":"adashino-nenbutsu-ji-temple","jword":"化野念仏寺","hiragana":"あだしのねんぶつじ"}
,
{"id":"52","eword":"sumiya-museum","jword":"角屋もてなしの文化美術館","hiragana":"すみやもてなしのぶんかびじゅつかん"}
,
{"id":"53","eword":"kyoto-national-museum","jword":"京都国立博物館","hiragana":"きょうとこくりつはくぶつかん"}
,
{"id":"54","eword":"manga-museum","jword":"京都国際マンガミュージアム","hiragana":"きょうとこくさいまんがみゅーじあむ"}
,
{"id":"55","eword":"puratto-kodama-ticket","jword":"ぷらっとこだまの切符","hiragana":"ぷらっとこだまのきっぷ"}
,
{"id":"56","eword":"uzumasa-tenjingawa-river","jword":"太秦天神川","hiragana":"うずまさてんりゅうがわ"}
,
{"id":"57","eword":"JR-underground-central-gate","jword":"地下中央口","hiragana":"ちかちゅうおうぐち"}
,
{"id":"58","eword":"sumiyamuseum","jword":"角屋もてなしの文化美術館","hiragana":"すみやもてなしのぶんかびじゅつかん"}
,
{"id":"59","eword":"toei-uzumasa-eigamura","jword":"東映太秦映画村","hiragana":"とうえいうずまさえいがむら"}
,
{"id":"60","eword":"tourist-information-center","jword":"観光案内所","hiragana":"かんこうあんないじょ"}
,
{"id":"61","eword":"tourist-information-office","jword":"観光案内所","hiragana":"かんこうあんないじょ"}
,
{"id":"62","eword":"kitashirakawatenjinmiya","jword":"北白川天神宮","hiragana":"きたしらかわてんじんみや"}
,
{"id":"63","eword":"kyotocenturyhotel","jword":"京都センチュリーホテル","hiragana":"きょうとせんちゅりーほてる"}
,
{"id":"64","eword":"hotelmystayskyoto","jword":"ホテルマイステイズ京都","hiragana":"ほてるまいすていずきょうと"}
,
{"id":"65","eword":"mangamuseum","jword":"京都国際マンガミュージアム","hiragana":"きょうとこくさいまんがみゅーじあむ"}
,
{"id":"66","eword":"kyoto-railway-museum","jword":"京都鉄道博物館","hiragana":"きょうとてつどうはくぶつかん"}
,
{"id":"67","eword":"rihgaroyalhotel","jword":"リーガロイヤルホテル京都","hiragana":"りーがろいやるほてるきょうと"}
,
{"id":"68","eword":"senshujikyotobekkan","jword":"専修寺京都別院","hiragana":"せんしゅうじきょうとべついん"}
,
{"id":"69","eword":"shugakuin-imperial-villa","jword":"修学院離宮","hiragana":"しゅうがくいんりきゅう"}
,
{"id":"70","eword":"kyotonationalmuseum","jword":"京都国立博物館","hiragana":"きょうとこくりつはくぶつかん"}
,
{"id":"71","eword":"kitashirakawa-tenjingu","jword":"北白川天神宮","hiragana":"きたしらかわてんじんみや"}
,
{"id":"72","eword":"granvia-kyoto","jword":"ホテルグランヴィア京都","hiragana":"ほてるぐらぐらんゔぃあきょうと"}
,
{"id":"73","eword":"kyotorailwaymuseum","jword":"京都鉄道博物館","hiragana":"きょうとてつどうはくぶつかん"}
,
{"id":"74","eword":"nagaoka-tenman-gu-shrine","jword":"長岡天満宮","hiragana":"ながおかてんまんぐう"}
,
{"id":"75","eword":"gokonomiya-jinja-shrine","jword":"御香宮神社","hiragana":"ごこうのみやじんじゃ"}
,
{"id":"76","eword":"touristinformationcenter","jword":"観光案内所","hiragana":"かんこうあんないじょ"}
,
{"id":"77","eword":"toeiuzumasaeigamura","jword":"東映太秦映画村","hiragana":"とうえいうずまさえいがむら"}
,
{"id":"78","eword":"granviakyoto","jword":"ホテルグランヴィア京都","hiragana":"ほてるぐらぐらんゔぃあきょうと"}
,
{"id":"79","eword":"otagi-nenbutsu-ji-temple","jword":"愛宕念仏寺","hiragana":"あたごねんぶつじ"}
,
{"id":"80","eword":"hotelnikko","jword":"ホテル日航プリンセス京都","hiragana":"ほてるにっこうぷりんせすきょうと"}
,
{"id":"81","eword":"toeikyotosatueijo","jword":"東映京都撮影所","hiragana":"とうえいきょうとさつえいじょ"}
,
{"id":"82","eword":"toei-kyoto-studio","jword":"東映京都撮影所","hiragana":"とうえいきょうとさつえいじょ"}
,
{"id":"83","eword":"kansai-international-airport","jword":"関西国際空港","hiragana":"かんくう"}
,
{"id":"84","eword":"subwayshijokarasuma","jword":"地下鉄四条烏丸","hiragana":"ちかてつしじょうからすま"}
,
{"id":"85","eword":"iwashimizu-hachimangu","jword":"石清水八幡宮","hiragana":"いわしみずはちまんぐう"}
,
{"id":"86","eword":"subwayshijikarasuma","jword":"地下鉄四条烏丸","hiragana":"ちかてつしじょうからすま"}
,
{"id":"87","eword":"underground-central-gate","jword":"地下中央口","hiragana":"ちかちゅうおうぐち"}
,
{"id":"88","eword":"shugakuinimperialvilla","jword":"修学院離宮","hiragana":"しゅうがくいんりきゅう"}
,
{"id":"89","eword":"uzumasa-koryu-ji-temple","jword":"太秦広隆寺","hiragana":"うずまさこうりゅうじ"}
,
{"id":"90","eword":"pontochokaburenjo","jword":"先斗町歌舞練場","hiragana":"ぽんとちょうかぶれんじょう"}
,
{"id":"91","eword":"kanku-limousine-bus","jword":"関空リムジンバス","hiragana":"かんくうりむじんばす"}
,
{"id":"92","eword":"akikonaishinonohaka","jword":"暲子内親王墓","hiragana":"あきこないしんのうのはか"}
,
{"id":"93","eword":"sarutahiko-jinja-shrine","jword":"猿田彦神社","hiragana":"さるたひこじんじゃ"}
,
{"id":"94","eword":"convenience-store","jword":"コンビニエンスストア","hiragana":"こんびにえんすすとあ"}
,
{"id":"95","eword":"konkai-komyo-ji-temple","jword":"金戒光明寺","hiragana":"こんかいこうみょうじ"}
,
{"id":"96","eword":"toganoo-kozan-ji-temple","jword":"栂尾高山寺","hiragana":"とがのおこうざんじ"}
,
{"id":"97","eword":"sankichi-inari-shrine","jword":"三吉稲荷","hiragana":"さんきちいなりじんじゃ"}
,
{"id":"98","eword":"hotel-mystays","jword":"ホテルマイステイズ京都","hiragana":"ほてるまいすていずきょうと"}
,
{"id":"99","eword":"hotelmystays","jword":"ホテルマイステイズ京都","hiragana":"ほてるまいすていずきょうと"}
,
{"id":"100","eword":"kyotoshiyakushomae","jword":"京都市役所前","hiragana":"きょうとしやくしょまえ"}
,
{"id":"101","eword":"kansaiinternationalairport","jword":"関西国際空港","hiragana":"かんくう"}
,
{"id":"102","eword":"kyoto-tower-hotel","jword":"京都タワーホテル","hiragana":"きょうとたわーほてる"}
,
{"id":"103","eword":"undergroundcentralgate","jword":"地下中央口","hiragana":"ちかちゅうおうぐち"}
,
{"id":"104","eword":"fushimi-inari-shrine","jword":"伏見稲荷大社","hiragana":"ふしみいなりたいしゃ"}
,
{"id":"105","eword":"multi-purpose-bathroom","jword":"多目的トイレ","hiragana":"たもくてきといれ"}
,
{"id":"106","eword":"higashi-hongan-ji-temple","jword":"東本願寺","hiragana":"ひがしほんがんじ"}
,
{"id":"107","eword":"kitano-tenmangu-shrine","jword":"北野天満宮","hiragana":"きたのてんまんぐう"}
,
{"id":"108","eword":"fujinomori-jinja-shrine","jword":"藤森神社","hiragana":"ふじのもりじんじゃ"}
,
{"id":"109","eword":"toeikyotostudio","jword":"東映京都撮影所","hiragana":"とうえいきょうとさつえいじょ"}
,
{"id":"110","eword":"shinmiyakohotel","jword":"新都ホテル京都","hiragana":"しんみやこほてるきょうと"}
,
{"id":"111","eword":"rokuharamitsu-ji-temple","jword":"六波羅蜜寺","hiragana":"ろくはらみつじ"}
,
{"id":"112","eword":"uzumasa-tenjingawa","jword":"太秦天神川","hiragana":"うずまさてんりゅうがわ"}
,
{"id":"113","eword":"shimogamo-jinja-shrine","jword":"下賀茂神社","hiragana":"しもがもじんじゃ"}
,
{"id":"114","eword":"adashino-nenbutsu-ji","jword":"化野念仏寺","hiragana":"あだしのねんぶつじ"}
,
{"id":"115","eword":"sagano-romantic-train","jword":"トロッコ嵯峨野","hiragana":"とろっこさがの"}
,
{"id":"116","eword":"JR-underground-east-gate","jword":"地下東口","hiragana":"ちかひがしぐち"}
,
{"id":"117","eword":"keihan-electric-railway","jword":"京阪電車","hiragana":"けいはんでんしゃ"}
,
{"id":"118","eword":"railway-museum","jword":"京都鉄道博物館","hiragana":"きょうとてつどうはくぶつかん"}
,
{"id":"119","eword":"umenomiya-taisha-shrine","jword":"梅宮大社","hiragana":"うめみやたいしゃ"}
,
{"id":"120","eword":"uzumasatenjingawa","jword":"太秦天神川","hiragana":"うずまさてんりゅうがわ"}
,
{"id":"121","eword":"railwaymuseum","jword":"京都鉄道博物館","hiragana":"きょうとてつどうはくぶつかん"}
,
{"id":"122","eword":"kansai-international-airport","jword":"関空","hiragana":"かんくう"}
,
{"id":"123","eword":"fukuoji-jinja-shrine","jword":"福王子神社","hiragana":"ふくおうじじんじゃ"}
,
{"id":"124","eword":"hino-tanjo-in-temple","jword":"日野誕生院","hiragana":"ひのたんじょういん"}
,
{"id":"125","eword":"multi-purpose-toilet","jword":"多目的トイレ","hiragana":"たもくてきといれ"}
,
{"id":"126","eword":"kamigamo-jinja-shrine","jword":"上賀茂神社","hiragana":"かみがもじんじゃ"}
,
{"id":"127","eword":"kintetsu-kyoto-line","jword":"近鉄京都線","hiragana":"きんてつきょうとせん"}
,
{"id":"128","eword":"kyototowerhotel","jword":"京都タワーホテル","hiragana":"きょうとたわーほてる"}
,
{"id":"129","eword":"kansaionedaypass","jword":"関西ワンデイパス","hiragana":"かんさいわんでぃぱす"}
,
{"id":"130","eword":"fushimiinaritaisha","jword":"伏見稲荷大社","hiragana":"ふしみいなりたいしゃ"}
,
{"id":"131","eword":"shiramine-jingu-shrine","jword":"白峯神宮","hiragana":"しらみねじんぐう"}
,
{"id":"132","eword":"sekizan-zen-in-temple","jword":"赤山禅院","hiragana":"せきざんぜんいん"}
,
{"id":"133","eword":"sankichinarijinja","jword":"三吉稲荷","hiragana":"さんきちいなりじんじゃ"}
,
{"id":"134","eword":"adashinonembutsuji","jword":"化野念仏寺","hiragana":"あだしのねんぶつじ"}
,
{"id":"135","eword":"yase-hieizanguchi","jword":"八瀬比叡山口","hiragana":"やせひえいざんぐち"}
,
{"id":"136","eword":"nishi-hongan-ji-temple","jword":"西本願寺","hiragana":"にしほんがんじ"}
,
{"id":"137","eword":"arashiyama-torokko","jword":"トロッコ嵐山","hiragana":"とろっこあらしやま"}
,
{"id":"138","eword":"omuro-ninna-ji-temple","jword":"御室仁和寺","hiragana":"おむろにんなじ"}
,
{"id":"139","eword":"saganoromantictrain","jword":"トロッコ嵯峨野","hiragana":"とろっこさがの"}
,
{"id":"140","eword":"keihanelectricrailway","jword":"京阪電車","hiragana":"けいはんでんしゃ"}
,
{"id":"141","eword":"ogoto-onsen-hot-spring","jword":"おごと温泉","hiragana":"おごとおんせ"}
,
{"id":"142","eword":"adashinonenbutsuji","jword":"化野念仏寺","hiragana":"あだしのねんぶつじ"}
,
{"id":"143","eword":"nagaoka-tenman-gu","jword":"長岡天満宮","hiragana":"ながおかてんまんぐう"}
,
{"id":"144","eword":"kintetsukyotoline","jword":"近鉄京都線","hiragana":"きんてつきょうとせん"}
,
{"id":"145","eword":"gokonomiya-jinja","jword":"御香宮神社","hiragana":"ごこうのみやじんじゃ"}
,
{"id":"146","eword":"katsura-imperial-villa","jword":"桂離宮","hiragana":"かつらりきゅう"}
,
{"id":"147","eword":"sento-imperial-palace","jword":"仙洞御所","hiragana":"せんとうごしょ"}
,
{"id":"148","eword":"underground-east-gate","jword":"地下東口","hiragana":"ちかひがしぐち"}
,
{"id":"149","eword":"universal-city","jword":"ユニバーサルシティ","hiragana":"ゆにばーさるしてぃ"}
,
{"id":"150","eword":"temawarihinkippu","jword":"手回り品きっぷ","hiragana":"てまわりひんきっぷ"}
,
{"id":"151","eword":"yasehieizanguchi","jword":"八瀬比叡山口","hiragana":"やせひえいざんぐち"}
,
{"id":"152","eword":"kyoto-imperial-palace","jword":"京都御所","hiragana":"きょうとごしょ"}
,
{"id":"153","eword":"dainitowerhotel","jword":"第二タワーホテル","hiragana":"だいにたわーほてる"}
,
{"id":"154","eword":"ajiwai-kan","jword":"京の食文化ミュージアムあじわい館","hiragana":"あじわいかん"}
,
{"id":"155","eword":"hino-hokai-ji-temple","jword":"日野法界寺","hiragana":"ひのほうかいじ"}
,
{"id":"156","eword":"imamiya-jinja-shrine","jword":"今宮神社","hiragana":"いまみやじんじゃ"}
,
{"id":"157","eword":"biwako-express","jword":"びわこエクスプレス","hiragana":"びわこえくすぷれす"}
,
{"id":"158","eword":"hotelkintetsu","jword":"ホテル近鉄京都駅","hiragana":"ほてるきんてつきょうと"}
,
{"id":"159","eword":"nipponrentacar","jword":"ニッポンレンタカー","hiragana":"にっぽんれんたかー"}
,
{"id":"160","eword":"hiyoshi-taisha-shrine","jword":"日吉大社","hiragana":"ひよしたいしゃ"}
,
{"id":"161","eword":"gokounomiyajinja","jword":"御香宮神社","hiragana":"ごこうのみやじんじゃ"}
,
{"id":"162","eword":"mangetsuukimido","jword":"満月寺浮御堂","hiragana":"まんげつじうきみどう"}
,
{"id":"163","eword":"usj","jword":"ユニバーサルスタジオジャパン","hiragana":"ゆにばーさるすたじおじゃぱん"}
,
{"id":"164","eword":"yoshida-jinja-shrine","jword":"吉田神社","hiragana":"よしだじんじゃ"}
,
{"id":"165","eword":"universalcity","jword":"ユニバーサルシティ","hiragana":"ゆにばーさるしてぃ"}
,
{"id":"166","eword":"atagonembutsutera","jword":"愛宕念仏寺","hiragana":"あたごねんぶつじ"}
,
{"id":"167","eword":"seimei-jinja-shrine","jword":"晴明神社","hiragana":"せいめいじんじゃ"}
,
{"id":"168","eword":"otagi-nenbutsu-ji","jword":"愛宕念仏寺","hiragana":"あたごねんぶつじ"}
,
{"id":"169","eword":"tokkyu-hashidate","jword":"特急はしだて","hiragana":"とっきゅうはしだて"}
,
{"id":"170","eword":"apahotel","jword":"アパホテル京都駅前","hiragana":"あぱほてるきょうとえきまえ"}
,
{"id":"171","eword":"uzumasa-koryu-ji","jword":"太秦広隆寺","hiragana":"うずまさこうりゅうじ"}
,
{"id":"172","eword":"nara-line-stair","jword":"奈良線階段下","hiragana":"ならせんかいだんした"}
,
{"id":"173","eword":"matsuo-taisha-shrine","jword":"松尾大社","hiragana":"まつおたいしゃ"}
,
{"id":"174","eword":"sarutahikojinnjya","jword":"猿田彦神社","hiragana":"さるたひこじんじゃ"}
,
{"id":"175","eword":"hozukyo-torokko","jword":"トロッコ保津峡","hiragana":"とろっこほずきょう"}
,
{"id":"176","eword":"jingu-marutamachi","jword":"神宮丸太町","hiragana":"じんぐうまるたまち"}
,
{"id":"177","eword":"midorinomadoguchi","jword":"みどりの窓口","hiragana":"みどりのまどぐち"}
,
{"id":"178","eword":"hatoya-zuihokaku","jword":"ハトヤ瑞鳳閣","hiragana":"はとやずいほうかく"}
,
{"id":"179","eword":"sankichi-inari","jword":"三吉稲荷","hiragana":"さんきちいなりじんじゃ"}
,
{"id":"180","eword":"heian-jingu-shrine","jword":"平安神宮","hiragana":"へいあんじんぐう"}
,
{"id":"181","eword":"uzumasa-eigamura","jword":"太秦映画村","hiragana":"うずまさえいがむら"}
,
{"id":"182","eword":"kifune-jinja-shrine","jword":"貴船神社","hiragana":"きふねじんじゃ"}
,
{"id":"183","eword":"shijokawaramachi","jword":"四条河原町","hiragana":"しじょうかわらまち"}
,
{"id":"184","eword":"kyotoimperialpalace","jword":"京都御所","hiragana":"きょうとごしょ"}
,
{"id":"185","eword":"toshodai-ji-temple","jword":"唐招提寺","hiragana":"とうしょうだいじ"}
,
{"id":"186","eword":"sarutahiko-jinja","jword":"猿田彦神社","hiragana":"さるたひこじんじゃ"}
,
{"id":"187","eword":"hatoyazuihokaku","jword":"ハトヤ瑞鳳閣","hiragana":"はとやずいほうかく"}
,
{"id":"188","eword":"kumano-jinja-shrine","jword":"熊野神社","hiragana":"くまのじんじゃ"}
,
{"id":"189","eword":"hirano-jinja-shrine","jword":"平野神社","hiragana":"ひらのじんじゃ"}
,
{"id":"190","eword":"yoshimine-dera-temple","jword":"善峯寺","hiragana":"よしみねでら"}
,
{"id":"191","eword":"undergroundeastgate","jword":"地下東口","hiragana":"ちかひがしぐち"}
,
{"id":"192","eword":"nagaokatenmangu","jword":"長岡天満宮","hiragana":"ながおかてんまんぐう"}
,
{"id":"193","eword":"jojakko-ji-temple","jword":"常寂光寺","hiragana":"じょうじゃくこうじ"}
,
{"id":"194","eword":"jingumarutamachi","jword":"神宮丸太町","hiragana":"じんぐうまるたまち"}
,
{"id":"195","eword":"philosopher-&s-path","jword":"哲学の道","hiragana":"てつがくのみち"}
,
{"id":"196","eword":"granviakyoto","jword":"グランヴィア京都","hiragana":"ぐらんゔぃあきょうと"}
,
{"id":"197","eword":"iorimachiyastay","jword":"庵町家ステイ","hiragana":"いおりまちやすてぃ"}
,
{"id":"198","eword":"luggage-ticket","jword":"手回り品きっぷ","hiragana":"てまわりひんきっぷ"}
,
{"id":"199","eword":"toganoo-kozan-ji","jword":"栂尾高山寺","hiragana":"とがのおこうざんじ"}
,
{"id":"200","eword":"yodobashi-camera","jword":"ヨドバシカメラ","hiragana":"よどばしかめら"}
,
{"id":"201","eword":"aeon-mall-location","jword":"イオンモール","hiragana":"いおんもーる"}
,
{"id":"202","eword":"katsuraimperialvilla","jword":"桂離宮","hiragana":"かつらりきゅう"}
,
{"id":"203","eword":"konkai-komyo-ji","jword":"金戒光明寺","hiragana":"こんかいこうみょうじ"}
,
{"id":"204","eword":"oishi-jinja-shrine","jword":"大石神社","hiragana":"おおいしじんじゃ"}
,
{"id":"205","eword":"shugakuinrikyu","jword":"修学院離宮","hiragana":"しゅうがくいんりきゅう"}
,
{"id":"206","eword":"yasaka-jinja-shrine","jword":"八坂神社","hiragana":"やさかじんじゃ"}
,
{"id":"207","eword":"yodobashicamera","jword":"ヨドバシカメラ","hiragana":"よどばしかめら"}
,
{"id":"208","eword":"kameoka-torokko","jword":"トロッコ亀岡","hiragana":"とろっこかめやま"}
,
{"id":"209","eword":"higashi-hongan-ji","jword":"東本願寺","hiragana":"ひがしほんがんじ"}
,
{"id":"210","eword":"kiyomizu-dera-temple","jword":"清水寺","hiragana":"きよみずでら"}
,
{"id":"211","eword":"uzumasaeigamura","jword":"太秦映画村","hiragana":"うずまさえいがむら"}
,
{"id":"212","eword":"luggageticket","jword":"手回り品きっぷ","hiragana":"てまわりひんきっぷ"}
,
{"id":"213","eword":"jishu-jinja-shrine","jword":"地主神社","hiragana":"じぬしじんじゃ"}
,
{"id":"214","eword":"fushimi-inari","jword":"伏見稲荷大社","hiragana":"ふしみいなりたいしゃ"}
,
{"id":"215","eword":"uzumasakoryuji","jword":"太秦広隆寺","hiragana":"うずまさこうりゅうじ"}
,
{"id":"216","eword":"gojokawaramachi","jword":"五条河原町","hiragana":"ごじょうかわらまち"}
,
{"id":"217","eword":"kitano-tenmangu","jword":"北野天満宮","hiragana":"きたのてんまんぐう"}
,
{"id":"218","eword":"sarutabikojinja","jword":"猿田彦神社","hiragana":"さるたひこじんじゃ"}
,
{"id":"219","eword":"tamokutekitoire","jword":"多目的トイレ","hiragana":"たもくてきといれ"}
,
{"id":"220","eword":"otaninokotsudo","jword":"大谷納骨堂","hiragana":"おおたにのうこつどう"}
,
{"id":"221","eword":"kyoto-aquarium","jword":"京都水族館","hiragana":"きょうとすいぞくかん"}
,
{"id":"222","eword":"ishiyama-dera-temple","jword":"石山寺","hiragana":"いしやまでら"}
,
{"id":"223","eword":"luggage-claim","jword":"忘れ物センター","hiragana":"わすれものせんたー"}
,
{"id":"224","eword":"supermarket","jword":"スーパーマーケット","hiragana":"すーぱーまーけっと"}
,
{"id":"225","eword":"hyotan-ji-temple","jword":"ひょうたん寺","hiragana":"ひょうたんてら"}
,
{"id":"226","eword":"100-yen-shop","jword":"100円ショップ","hiragana":"ひゃくえんしょっぷ"}
,
{"id":"227","eword":"awata-jinja-shrine","jword":"粟田神社","hiragana":"あわたじんじゃ"}
,
{"id":"228","eword":"hokongo-in-temple","jword":"法金剛院","hiragana":"ほうこんごういん"}
,
{"id":"229","eword":"otaginenbutsuji","jword":"愛宕念仏寺","hiragana":"あたごねんぶつじ"}
,
{"id":"230","eword":"sanjusangendo","jword":"三十三間堂","hiragana":"さんじゅうさんげんどう"}
,
{"id":"231","eword":"konkaikyomyoji","jword":"金戒光明寺","hiragana":"こんかいこうみょうじ"}
,
{"id":"232","eword":"fujinomori-jinja","jword":"藤森神社","hiragana":"ふじのもりじんじゃ"}
,
{"id":"233","eword":"umenomiya-taisha","jword":"梅宮大社","hiragana":"うめみやたいしゃ"}
,
{"id":"234","eword":"kiyomizudera-temple","jword":"清水寺","hiragana":"きよみずでら"}
,
{"id":"235","eword":"kyotoimperialpalace","jword":"御所","hiragana":"きょうとごしょ"}
,
{"id":"236","eword":"rokuharamitsu-ji","jword":"六波羅蜜寺","hiragana":"ろくはらみつじ"}
,
{"id":"237","eword":"oharasanzenin","jword":"大原三千院","hiragana":"おおはらさんぜんいん"}
,
{"id":"238","eword":"souvenir-department","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"239","eword":"kyoto-university","jword":"京都大学","hiragana":"きょうとだいがく"}
,
{"id":"240","eword":"fushimiinari","jword":"伏見稲荷大社","hiragana":"ふしみいなりたいしゃ"}
,
{"id":"241","eword":"lostandfound","jword":"忘れ物センター","hiragana":"わすれものせんたー"}
,
{"id":"242","eword":"shimogamo-jinja","jword":"下賀茂神社","hiragana":"しもがもじんじゃ"}
,
{"id":"243","eword":"toganookozanji","jword":"栂尾高山寺","hiragana":"とがのおこうざんじ"}
,
{"id":"244","eword":"otokuni-dera-temple","jword":"乙訓寺","hiragana":"おとくにてら"}
,
{"id":"245","eword":"gogoichihorai","jword":"551蓬莱","hiragana":"ごうごういちほうらい"}
,
{"id":"246","eword":"kurumaorijinjya","jword":"車折神社","hiragana":"くるまおりじんじゃ"}
,
{"id":"247","eword":"zennikkuhotel","jword":"全日空ホテル","hiragana":"ぜんにっくうほてる"}
,
{"id":"248","eword":"heianjingushrine","jword":"平安神宮","hiragana":"へいあんじんぐう"}
,
{"id":"249","eword":"sagano-torokko","jword":"トロッコ嵯峨野","hiragana":"とろっこさがの"}
,
{"id":"250","eword":"kurama-dera-temple","jword":"鞍馬寺","hiragana":"くらまやまでら"}
,
{"id":"251","eword":"fujinomorijinja","jword":"藤森神社","hiragana":"ふじのもりじんじゃ"}
,
{"id":"252","eword":"waiting-place","jword":"待ち合わせ場所","hiragana":"まちあわせばしょ"}
,
{"id":"253","eword":"kitanotenmangu","jword":"北野天満宮","hiragana":"きたのてんまんぐう"}
,
{"id":"254","eword":"rokuharamitsuji","jword":"六波羅蜜寺","hiragana":"ろくはらみつじ"}
,
{"id":"255","eword":"kamigamo-jinja","jword":"上賀茂神社","hiragana":"かみがもじんじゃ"}
,
{"id":"256","eword":"kameya-yoshinaga","jword":"亀屋良長","hiragana":"かめやよしなが"}
,
{"id":"257","eword":"yoshinaga-kameya","jword":"亀屋良長","hiragana":"かめやよしなが"}
,
{"id":"258","eword":"hankyu-railway","jword":"阪急電車","hiragana":"はんきゅうでんしゃ"}
,
{"id":"259","eword":"family-mart","jword":"ファミリーマート","hiragana":"ふぁみりーまーと"}
,
{"id":"260","eword":"tokaido-line","jword":"東海道本線","hiragana":"とうかいどうほんせん"}
,
{"id":"261","eword":"taikyokudenato","jword":"大極殿跡","hiragana":"たいきょくでんあと"}
,
{"id":"262","eword":"umenomiyataisha","jword":"梅宮大社","hiragana":"うめみやたいしゃ"}
,
{"id":"263","eword":"shimogamojinja","jword":"下賀茂神社","hiragana":"しもがもじんじゃ"}
,
{"id":"264","eword":"miyakojikaisoku","jword":"都路快速","hiragana":"みやこじかいそく"}
,
{"id":"265","eword":"gokomiyajinja","jword":"御香宮神社","hiragana":"ごこうみやじんじゃ"}
,
{"id":"266","eword":"wating_place","jword":"待ち合わせ場所","hiragana":"まちあわせばしょ"}
,
{"id":"267","eword":"fukuoji-jinja","jword":"福王子神社","hiragana":"ふくおうじじんじゃ"}
,
{"id":"268","eword":"hozu-gawa-river","jword":"保津川下り","hiragana":"ほずがわくだり"}
,
{"id":"269","eword":"ota-jinja-shrine","jword":"太田神社","hiragana":"おおたじんじゃ"}
,
{"id":"270","eword":"hino-tanjo-in","jword":"日野誕生院","hiragana":"ひのたんじょういん"}
,
{"id":"271","eword":"katata-ukimido","jword":"堅田浮御堂","hiragana":"かただうきみどう"}
,
{"id":"272","eword":"higashihonganji","jword":"東本願寺","hiragana":"ひがしほんがんじ"}
,
{"id":"273","eword":"chishaku-in-temple","jword":"智積院","hiragana":"ちしゃくいん"}
,
{"id":"274","eword":"kyotouniversity","jword":"京都大学","hiragana":"きょうとだいがく"}
,
{"id":"275","eword":"mimuroto-ji-temple","jword":"三室戸寺","hiragana":"みむろとじ"}
,
{"id":"276","eword":"kurumaorijinja","jword":"車折神社","hiragana":"くるまおりじんじゃ"}
,
{"id":"277","eword":"tetsugakunomichi","jword":"哲学の道","hiragana":"てつがくのみち"}
,
{"id":"278","eword":"ticket-office","jword":"チケット売り場","hiragana":"ちけっとうりば"}
,
{"id":"279","eword":"sanjo-keihan","jword":"三条京阪","hiragana":"さんじょうけいはん"}
,
{"id":"280","eword":"hokkaido-event","jword":"北海道展","hiragana":"ほっかいどうてん"}
,
{"id":"281","eword":"kamigamojinja","jword":"上賀茂神社","hiragana":"かみがもじんじゃ"}
,
{"id":"282","eword":"watingplace","jword":"待ち合わせ場所","hiragana":"まちあわせばしょ"}
,
{"id":"283","eword":"ryotoku-ji-temple","jword":"了徳寺","hiragana":"りょうとくじ"}
,
{"id":"284","eword":"myoshin-ji-temple","jword":"妙心寺","hiragana":"みょうしんじ"}
,
{"id":"285","eword":"familymart","jword":"ファミリーマート","hiragana":"ふぁみりーまーと"}
,
{"id":"286","eword":"highway-bus-stop","jword":"高速バス","hiragana":"こうそくばす"}
,
{"id":"287","eword":"shoren-in-temple","jword":"青蓮院","hiragana":"しょうれんいん"}
,
{"id":"288","eword":"shijo-karasuma","jword":"四条烏丸","hiragana":"しじょうからすま"}
,
{"id":"289","eword":"kokusaikaikan","jword":"国際会館","hiragana":"こくさいかいかん"}
,
{"id":"290","eword":"nenbutsu-ji-temple","jword":"念仏寺","hiragana":"ねんぶつじ"}
,
{"id":"291","eword":"nishioojioike","jword":"西大路御池","hiragana":"にしおおじおいけ"}
,
{"id":"292","eword":"enryaku-ji-temple","jword":"延暦寺","hiragana":"えんりゃくじ"}
,
{"id":"293","eword":"katadaukimido","jword":"堅田浮御堂","hiragana":"かただうきみどう"}
,
{"id":"294","eword":"nimotsuazukari","jword":"荷物預かり","hiragana":"にもつあづかり"}
,
{"id":"295","eword":"ruriko-in-temple","jword":"瑠璃光院","hiragana":"るりこういん"}
,
{"id":"296","eword":"saga-arashiyama","jword":"嵯峨嵐山","hiragana":"さがあらしやま"}
,
{"id":"297","eword":"nishi-hongan-ji","jword":"西本願寺","hiragana":"にしほんがんじ"}
,
{"id":"298","eword":"hozugawakudari","jword":"保津川下り","hiragana":"ほずがわくだり"}
,
{"id":"299","eword":"umekoji-park","jword":"梅小路公園","hiragana":"うめこうじこうえん"}
,
{"id":"300","eword":"hankyurailway","jword":"阪急電車","hiragana":"はんきゅうでんしゃ"}
,
{"id":"301","eword":"keikyu-in-temple","jword":"桂宮院","hiragana":"けいきゅういん"}
,
{"id":"302","eword":"imperial-palace","jword":"京都御所","hiragana":"きょうとごしょ"}
,
{"id":"303","eword":"shokoku-ji-temple","jword":"相国寺","hiragana":"しょうこくじ"}
,
{"id":"304","eword":"saganotrokko","jword":"トロッコ嵯峨野","hiragana":"とろっこさがの"}
,
{"id":"305","eword":"fukuojijinja","jword":"福王子神社","hiragana":"ふくおうじじんじゃ"}
,
{"id":"306","eword":"shiraminejungu","jword":"白峯神宮","hiragana":"しらみねじんぐう"}
,
{"id":"307","eword":"katsuranomiyain","jword":"桂宮院","hiragana":"かつらのみやいん"}
,
{"id":"308","eword":"tsugaokosanji","jword":"栂尾高山寺","hiragana":"つがおこうさんじ"}
,
{"id":"309","eword":"omuro-ninna-ji","jword":"御室仁和寺","hiragana":"おむろにんなじ"}
,
{"id":"310","eword":"bus-information","jword":"バス情報","hiragana":"ばすじょうほう"}
,
{"id":"311","eword":"sekizan-zen-in","jword":"赤山禅院","hiragana":"せきざんぜんいん"}
,
{"id":"312","eword":"tokaidoline","jword":"東海道本線","hiragana":"とうかいどうほんせん"}
,
{"id":"313","eword":"nishioji-oike","jword":"西大路御池","hiragana":"にしおおじおいけ"}
,
{"id":"314","eword":"hankyu-train","jword":"阪急電車","hiragana":"はんきゅうでんしゃ"}
,
{"id":"315","eword":"higashi-okayama","jword":"東岡山","hiragana":"ひがしおかやま"}
,
{"id":"316","eword":"manshu-in-temple","jword":"曼殊院","hiragana":"まんしゅいん"}
,
{"id":"317","eword":"shijokarasuma","jword":"四条烏丸","hiragana":"しじょうからすま"}
,
{"id":"318","eword":"kinkaku-ji-temple","jword":"金閣寺","hiragana":"きんかくじ"}
,
{"id":"319","eword":"western-style-food","jword":"洋食","hiragana":"ようしょく"}
,
{"id":"320","eword":"fujimorijinja","jword":"藤森神社","hiragana":"ふじもりじんじゃ"}
,
{"id":"321","eword":"manpuku-ji-temple","jword":"萬福寺","hiragana":"まんぷくじ"}
,
{"id":"322","eword":"jonan-gu-shrine","jword":"城南宮","hiragana":"じょうなんぐう"}
,
{"id":"323","eword":"souvenir-section","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"324","eword":"karasuma-oike","jword":"烏丸御池","hiragana":"からすまおいけ"}
,
{"id":"325","eword":"hino-hokai-ji","jword":"日野法界寺","hiragana":"ひのほうかいじ"}
,
{"id":"326","eword":"imperialpalace","jword":"京都御所","hiragana":"きょうとごしょ"}
,
{"id":"327","eword":"daikaku-ji-temple","jword":"大覚寺","hiragana":"だいかくじ"}
,
{"id":"328","eword":"daisen-in-temple","jword":"大仙院","hiragana":"だいせんいん"}
,
{"id":"329","eword":"shoseien-garden","jword":"渉成園","hiragana":"しょうせいえん"}
,
{"id":"330","eword":"daitoku-ji-temple","jword":"大徳寺","hiragana":"だいとくじ"}
,
{"id":"331","eword":"imamiya-jinja","jword":"今宮神社","hiragana":"いまみやじんじゃ"}
,
{"id":"332","eword":"coin-locker","jword":"コインロッカー","hiragana":"こいんろっかー"}
,
{"id":"333","eword":"kyotoajiwaikan","jword":"あじわい館","hiragana":"あじわいかん"}
,
{"id":"334","eword":"byodo-in-temple","jword":"平等院","hiragana":"びょうどういん"}
,
{"id":"335","eword":"josho-ji-temple","jword":"常照寺","hiragana":"じょうしょうじ"}
,
{"id":"336","eword":"sennyu-ji-temple","jword":"泉涌寺","hiragana":"せんにゅうじ"}
,
{"id":"337","eword":"nisihihonganji","jword":"西本願寺","hiragana":"にしほんがんじ"}
,
{"id":"338","eword":"granvia","jword":"グランヴィア京都","hiragana":"ぐらんゔぃあきょうと"}
,
{"id":"339","eword":"seiryo-ji-temple","jword":"清涼寺","hiragana":"せいりょうじ"}
,
{"id":"340","eword":"ginkaku-ji-temple","jword":"銀閣寺","hiragana":"ぎんかくじ"}
,
{"id":"341","eword":"katsura-gawa-river","jword":"桂川","hiragana":"かつらがわ"}
,
{"id":"342","eword":"hinotanjoin","jword":"日野誕生院","hiragana":"ひのたんじょういん"}
,
{"id":"343","eword":"elinnkyoto","jword":"エルイン京都","hiragana":"えるいんきょうと"}
,
{"id":"344","eword":"hankyu-hotel","jword":"阪急ホテル","hiragana":"はんきゅうほてる"}
,
{"id":"345","eword":"hokkaidoevent","jword":"北海道展","hiragana":"ほっかいどうてん"}
,
{"id":"346","eword":"thunderbird","jword":"サンダーバード","hiragana":"サンダーバード"}
,
{"id":"347","eword":"miyakehachiman","jword":"三宅八幡","hiragana":"みやけはちまん"}
,
{"id":"348","eword":"maruyama-park","jword":"円山公園","hiragana":"まるやまこうえん"}
,
{"id":"349","eword":"hiyoshi-taisha","jword":"日吉大社","hiragana":"ひよしたいしゃ"}
,
{"id":"350","eword":"tenryu-ji-temple","jword":"天龍寺","hiragana":"てんりゅうじ"}
,
{"id":"351","eword":"umemiyataisha","jword":"梅宮大社","hiragana":"うめみやたいしゃ"}
,
{"id":"352","eword":"sanjokeihan","jword":"三条京阪","hiragana":"さんじょうけいはん"}
,
{"id":"353","eword":"sagaarashiyama","jword":"嵯峨嵐山","hiragana":"さがあらしやま"}
,
{"id":"354","eword":"karasumaoike","jword":"烏丸御池","hiragana":"からすまおいけ"}
,
{"id":"355","eword":"sekizansenin","jword":"赤山禅院","hiragana":"せきざんぜんいん"}
,
{"id":"356","eword":"koryu-ji-temple","jword":"広隆寺","hiragana":"こうりゅうじ"}
,
{"id":"357","eword":"komyo-ji-temple","jword":"光明寺","hiragana":"こうみょうじ"}
,
{"id":"358","eword":"daisen-ji-temple","jword":"大仙寺","hiragana":"だいせんじ"}
,
{"id":"359","eword":"hiyoshitaisha","jword":"日吉大社","hiragana":"ひよしたいしゃ"}
,
{"id":"360","eword":"hankyuhotel","jword":"阪急ホテル","hiragana":"はんきゅうほてる"}
,
{"id":"361","eword":"hankyutrain","jword":"阪急電車","hiragana":"はんきゅうでんしゃ"}
,
{"id":"362","eword":"ryoan-ji-temple","jword":"龍安寺","hiragana":"りょうあんじ"}
,
{"id":"363","eword":"keihan-line","jword":"京阪電車","hiragana":"けいきゅうでんしゃ"}
,
{"id":"364","eword":"taxi-stand","jword":"タクシーのりば","hiragana":"たくしーのりば"}
,
{"id":"365","eword":"jurakudaiato","jword":"聚楽第跡","hiragana":"じゅらくだいあと"}
,
{"id":"366","eword":"higashiokayama","jword":"東岡山","hiragana":"ひがしおかやま"}
,
{"id":"367","eword":"usj","jword":"ユニバーサルスタジオジャパン","hiragana":"ゆーえすじぇい"}
,
{"id":"368","eword":"ana-hotel","jword":"全日空ホテル","hiragana":"ぜんにっくうほてる"}
,
{"id":"369","eword":"imamiyajinja","jword":"今宮神社","hiragana":"いまみやじんじゃ"}
,
{"id":"370","eword":"tokyu-hands","jword":"東急ハンズ","hiragana":"とうきゅうはんず"}
,
{"id":"371","eword":"money-exchange","jword":"両替所","hiragana":"りょうがえじょ"}
,
{"id":"372","eword":"koetsu-ji-temple","jword":"光悦寺","hiragana":"こうえつじ"}
,
{"id":"373","eword":"nanzen-ji-temple","jword":"南禅寺","hiragana":"なんぜんじ"}
,
{"id":"374","eword":"tofuku-ji-temple","jword":"東福寺","hiragana":"とうふくじ"}
,
{"id":"375","eword":"yoshida-jinja","jword":"吉田神社","hiragana":"よしだじんじゃ"}
,
{"id":"376","eword":"genko-ji-temple","jword":"源光庵","hiragana":"げんこうあん"}
,
{"id":"377","eword":"ebisu-shrine","jword":"えびす神社","hiragana":"えびすじんじゃ"}
,
{"id":"378","eword":"amanohashidate","jword":"天橋立","hiragana":"あまのはしだて"}
,
{"id":"379","eword":"omuroninnaji","jword":"御室仁和寺","hiragana":"おむろにんなじ"}
,
{"id":"380","eword":"kennin-ji-temple","jword":"建仁寺","hiragana":"けんにんじ"}
,
{"id":"381","eword":"coinlocker","jword":"コインロッカー","hiragana":"こいんろっかー"}
,
{"id":"382","eword":"around-station","jword":"駅周辺","hiragana":"えきしゅうへん"}
,
{"id":"383","eword":"hokyo-ji-temple","jword":"法鏡寺","hiragana":"ほうきょうじ"}
,
{"id":"384","eword":"matsuo-taisha","jword":"松尾大社","hiragana":"まつおたいしゃ"}
,
{"id":"385","eword":"tokyu-hotel","jword":"東急ホテル","hiragana":"とうきゅうほてる"}
,
{"id":"386","eword":"seimei-jinja","jword":"晴明神社","hiragana":"せいめいじんじゃ"}
,
{"id":"387","eword":"maruyamakoen","jword":"円山公園","hiragana":"まるやまこうえん"}
,
{"id":"388","eword":"souvenirsection","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"389","eword":"kuramayamadera","jword":"鞍馬寺","hiragana":"くらまやまでら"}
,
{"id":"390","eword":"luggage-room","jword":"荷物預かり","hiragana":"にもつあづかり"}
,
{"id":"391","eword":"zenrin-ji-temple","jword":"禅林寺","hiragana":"ぜんりんじ"}
,
{"id":"392","eword":"taizo-in-temple","jword":"退蔵院","hiragana":"たいぞういん"}
,
{"id":"393","eword":"kiyomizu-temple","jword":"清水寺","hiragana":"きよみずでら"}
,
{"id":"394","eword":"nishiki-market","jword":"錦市場","hiragana":"にしきいちば"}
,
{"id":"395","eword":"honen-in-temple","jword":"法然院","hiragana":"ほうねいん"}
,
{"id":"396","eword":"awata-shrine","jword":"粟田神社","hiragana":"あわたじんじゃ"}
,
{"id":"397","eword":"jojakko-ji","jword":"常寂光寺","hiragana":"じょうじゃくこうじ"}
,
{"id":"398","eword":"luggageroom","jword":"荷物預かり","hiragana":"にもつあづかり"}
,
{"id":"399","eword":"mibu-dera-temple","jword":"壬生寺","hiragana":"みぶでら"}
,
{"id":"400","eword":"toshodai-ji","jword":"唐招提寺","hiragana":"とうしょうだいじ"}
,
{"id":"401","eword":"hirano-jinja","jword":"平野神社","hiragana":"ひらのじんじゃ"}
,
{"id":"402","eword":"seimeijinja","jword":"晴明神社","hiragana":"せいめいじんじゃ"}
,
{"id":"403","eword":"kitsuenbasho","jword":"喫煙場所","hiragana":"きつえんばしょ"}
,
{"id":"404","eword":"smoking-area","jword":"喫煙場所","hiragana":"きつえんばしょ"}
,
{"id":"405","eword":"kumano-jinja","jword":"熊野神社","hiragana":"くまのじんじゃ"}
,
{"id":"406","eword":"kyoto-souvenir","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"407","eword":"jisso-in-temple","jword":"実相院","hiragana":"じっそうじ"}
,
{"id":"408","eword":"kifune-jinja","jword":"貴船神社","hiragana":"きふねじんじゃ"}
,
{"id":"409","eword":"yoshidajinja","jword":"吉田神社","hiragana":"よしだじんじゃ"}
,
{"id":"410","eword":"starbucks","jword":"スターバックス","hiragana":"すたーばっくす"}
,
{"id":"411","eword":"keihanline","jword":"京阪電車","hiragana":"けいきゅうでんしゃ"}
,
{"id":"412","eword":"kinzo-ji-temple","jword":"金蔵寺","hiragana":"こんぞうじ"}
,
{"id":"413","eword":"shuttle-bus","jword":"シャトルバス","hiragana":"しゃとるばす"}
,
{"id":"414","eword":"kodai-ji-temple","jword":"高台寺","hiragana":"こうだいじ"}
,
{"id":"415","eword":"drugstore","jword":"ドラッグストア","hiragana":"どらっぐすとあ"}
,
{"id":"416","eword":"nursing-room","jword":"授乳室","hiragana":"じゅにゅうしつ"}
,
{"id":"417","eword":"anahotel","jword":"全日空ホテル","hiragana":"ぜんにっくうほてる"}
,
{"id":"418","eword":"shoji-ji-temple","jword":"勝持寺","hiragana":"しょうじじ"}
,
{"id":"419","eword":"oishi-jinja","jword":"大石神社","hiragana":"おおいしじんじゃ"}
,
{"id":"420","eword":"tokyuhands","jword":"東急ハンズ","hiragana":"とうきゅうはんず"}
,
{"id":"421","eword":"heian-jingu","jword":"平安神宮","hiragana":"へいあんじんぐう"}
,
{"id":"422","eword":"saiho-ji-temple","jword":"西芳寺","hiragana":"さいほうじ"}
,
{"id":"423","eword":"hinohokaiji","jword":"日野法界寺","hiragana":"ひのほうかいじ"}
,
{"id":"424","eword":"hokai-ji-temple","jword":"法界寺","hiragana":"ほうかいじ"}
,
{"id":"425","eword":"horin-ji-temple","jword":"法輪寺","hiragana":"ほうりんじ"}
,
{"id":"426","eword":"westernstylefood","jword":"洋食","hiragana":"ようしょく"}
,
{"id":"427","eword":"suzakumonato","jword":"朱雀門跡","hiragana":"すざくもんあと"}
,
{"id":"428","eword":"kyoto-cuisine","jword":"京料理","hiragana":"きょうりょうり"}
,
{"id":"429","eword":"moneyexchange","jword":"両替所","hiragana":"りょうがえじょ"}
,
{"id":"430","eword":"hyotantera","jword":"ひょうたん寺","hiragana":"ひょうたんてら"}
,
{"id":"431","eword":"hyotan-jie","jword":"ひょうたん寺","hiragana":"ひょうたんてら"}
,
{"id":"432","eword":"nison-in-temple","jword":"二尊院","hiragana":"にそんいん"}
,
{"id":"433","eword":"kyoto-tower","jword":"京都タワー","hiragana":"きょうとたわー"}
,
{"id":"434","eword":"shogoin-temple","jword":"聖護院","hiragana":"しょうごいん"}
,
{"id":"435","eword":"yasaka-jinja","jword":"八坂神社","hiragana":"やさかじんじゃ"}
,
{"id":"436","eword":"kyoto-gyoen","jword":"京都御苑","hiragana":"きょうとぎょえん"}
,
{"id":"437","eword":"tokyuhotel","jword":"東急ホテル","hiragana":"とうきゅうほてる"}
,
{"id":"438","eword":"kamitobaguchi","jword":"上鳥羽口","hiragana":"かみとばぐち"}
,
{"id":"439","eword":"matsuotaisha","jword":"松尾大社","hiragana":"まつおたいしゃ"}
,
{"id":"440","eword":"hida-takayama","jword":"飛騨高山","hiragana":"ひだたかやま"}
,
{"id":"441","eword":"nishiki-ichiba","jword":"錦市場","hiragana":"にしきいちば"}
,
{"id":"442","eword":"honno-ji-temple","jword":"本能寺","hiragana":"ほんのうじ"}
,
{"id":"443","eword":"jinushijinja","jword":"地主神社","hiragana":"じぬしじんじゃ"}
,
{"id":"444","eword":"chukyoriken","jword":"中距離券","hiragana":"ちゅうきょりけん"}
,
{"id":"445","eword":"tokkyu-ticket","jword":"特急券","hiragana":"とっきゅうけん"}
,
{"id":"446","eword":"jojakukoji","jword":"常寂光寺","hiragana":"じょうじゃくこうじ"}
,
{"id":"447","eword":"nijojomae","jword":"二条城前","hiragana":"にじょうじょうまえ"}
,
{"id":"448","eword":"suzumushidera","jword":"鈴虫寺","hiragana":"すずむしでら"}
,
{"id":"449","eword":"starbuck","jword":"スターバックス","hiragana":"すたーばっくす"}
,
{"id":"450","eword":"tennoji-temple","jword":"天王寺","hiragana":"てんのうじ"}
,
{"id":"451","eword":"JR-west-entrance","jword":"西口","hiragana":"にしぐち"}
,
{"id":"452","eword":"kintetsu-line","jword":"近鉄線","hiragana":"きんてつせん"}
,
{"id":"453","eword":"rajomonato","jword":"羅城門跡","hiragana":"らじょうもんあと"}
,
{"id":"454","eword":"kifunejinja","jword":"貴船神社","hiragana":"きふねじんじゃ"}
,
{"id":"455","eword":"souvenir-shop","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"456","eword":"ogoto-onsen","jword":"おごと温泉","hiragana":"おごとおんせ"}
,
{"id":"457","eword":"famima","jword":"ファミリーマート","hiragana":"ふぁみりーまーと"}
,
{"id":"458","eword":"karasumaguchi","jword":"烏丸口","hiragana":"からすまぐち"}
,
{"id":"459","eword":"hachijo-exit","jword":"八条口","hiragana":"はちじょうぐち"}
,
{"id":"460","eword":"hachijoguchi","jword":"八条口","hiragana":"はちじょうぐち"}
,
{"id":"461","eword":"enko-ji-temple","jword":"圓光寺","hiragana":"えんこうじ"}
,
{"id":"462","eword":"mii-dera-temple","jword":"三井寺","hiragana":"みいでら"}
,
{"id":"463","eword":"hoon-ji-temple","jword":"報恩寺","hiragana":"ほうおんじ"}
,
{"id":"464","eword":"sasayamaguchi","jword":"篠山口","hiragana":"ささやまぐち"}
,
{"id":"465","eword":"rozan-ji-temple","jword":"廬山寺","hiragana":"ろざんじ"}
,
{"id":"466","eword":"yasakajinja","jword":"八坂神社","hiragana":"やさかじんじゃ"}
,
{"id":"467","eword":"daigo-ji-temple","jword":"醍醐寺","hiragana":"だいごじ"}
,
{"id":"468","eword":"kiyomizu-dera","jword":"清水寺","hiragana":"きよみずでら"}
,
{"id":"469","eword":"gion-festival","jword":"祇園祭","hiragana":"ぎおんまつり"}
,
{"id":"470","eword":"machiaishitsu","jword":"待合室","hiragana":"まちあいしつ"}
,
{"id":"471","eword":"katsurarikyu","jword":"桂離宮","hiragana":"かつらりきゅう"}
,
{"id":"472","eword":"jingo-ji-temple","jword":"神護寺","hiragana":"じんごじ"}
,
{"id":"473","eword":"resting-room","jword":"休憩所","hiragana":"きゅうけいじょ"}
,
{"id":"474","eword":"bishamon-do","jword":"毘沙門堂","hiragana":"びしゃもんどう"}
,
{"id":"475","eword":"nishikimarket","jword":"錦市場","hiragana":"にしきいちば"}
,
{"id":"476","eword":"toshodaiji","jword":"唐招提寺","hiragana":"とうしょうだいじ"}
,
{"id":"477","eword":"toji-in-temple","jword":"等持院","hiragana":"とうじいん"}
,
{"id":"478","eword":"nishikiichiba","jword":"錦市場","hiragana":"にしきいちば"}
,
{"id":"479","eword":"bic-camera","jword":"ビックカメラ","hiragana":"びっくかめら"}
,
{"id":"480","eword":"hidatakayama","jword":"飛騨高山","hiragana":"ひだたかやま"}
,
{"id":"481","eword":"kyototower","jword":"京都タワー","hiragana":"きょうとたわー"}
,
{"id":"482","eword":"hokongo-in","jword":"法金剛院","hiragana":"ほうこんごういん"}
,
{"id":"483","eword":"ninna-ji-temple","jword":"仁和寺","hiragana":"にんなじ"}
,
{"id":"484","eword":"stationbuilding","jword":"駅ビル","hiragana":"えきびる"}
,
{"id":"485","eword":"jishu-jinja","jword":"地主神社","hiragana":"じぬしじんじゃ"}
,
{"id":"486","eword":"money-change","jword":"両替所","hiragana":"りょうがえじょ"}
,
{"id":"487","eword":"hiranojinja","jword":"平野神社","hiragana":"ひらのじんじゃ"}
,
{"id":"488","eword":"nursingroom","jword":"授乳室","hiragana":"じゅにゅうしつ"}
,
{"id":"489","eword":"kyotocuisine","jword":"京料理","hiragana":"きょうりょうり"}
,
{"id":"490","eword":"ebisujinja","jword":"えびす神社","hiragana":"えびすじんじゃ"}
,
{"id":"491","eword":"karasuma-line","jword":"烏丸線","hiragana":"からすません"}
,
{"id":"492","eword":"chion-in-temple","jword":"知恩院","hiragana":"ちおいん"}
,
{"id":"493","eword":"renta-a-car","jword":"レンターカー","hiragana":"れんたかー"}
,
{"id":"494","eword":"hoko-ji-temple","jword":"方広寺","hiragana":"ほうこうじ"}
,
{"id":"495","eword":"ishiyama-dera","jword":"石山寺","hiragana":"いしやまでら"}
,
{"id":"496","eword":"kegon-ji-temple","jword":"華厳寺","hiragana":"けごんじ"}
,
{"id":"497","eword":"oishijinja","jword":"大石神社","hiragana":"おおいしじんじゃ"}
,
{"id":"498","eword":"heianjingu","jword":"平安神宮","hiragana":"へいあんじんぐう"}
,
{"id":"499","eword":"kyotogyoen","jword":"京都御苑","hiragana":"きょうとぎょえん"}
,
{"id":"500","eword":"kinkyoriken","jword":"近距離券","hiragana":"きんきょりけん"}
,
{"id":"501","eword":"smokingarea","jword":"喫煙場所","hiragana":"きつえんばしょ"}
,
{"id":"502","eword":"kumanojinja","jword":"熊野神社","hiragana":"くまのじんじゃ"}
,
{"id":"503","eword":"jr-amagasaki","jword":"JR尼崎","hiragana":"あまがさき"}
,
{"id":"504","eword":"kurama-dera","jword":"鞍馬寺","hiragana":"くらまやまでら"}
,
{"id":"505","eword":"aeon-mall","jword":"イオンモール","hiragana":"いおんもーる"}
,
{"id":"506","eword":"gion-shijo","jword":"祇園四条","hiragana":"ぎおんしじょう"}
,
{"id":"507","eword":"gionfestival","jword":"祇園祭","hiragana":"ぎおんまつり"}
,
{"id":"508","eword":"souvenirshop","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"509","eword":"awatajinja","jword":"粟田神社","hiragana":"あわたじんじゃ"}
,
{"id":"510","eword":"biccamera","jword":"ビックカメラ","hiragana":"びっくかめら"}
,
{"id":"511","eword":"ajari-mochi","jword":"阿闍梨餅","hiragana":"あじゃりもち"}
,
{"id":"512","eword":"gion-ji-temple","jword":"祇園寺","hiragana":"ぎおんじ"}
,
{"id":"513","eword":"kyotogosho","jword":"京都御所","hiragana":"きょうとごしょ"}
,
{"id":"514","eword":"kiyomizudera","jword":"清水寺","hiragana":"きよみずでら"}
,
{"id":"515","eword":"ogotoonsen","jword":"おごと温泉","hiragana":"おごとおんせ"}
,
{"id":"516","eword":"restingroom","jword":"休憩所","hiragana":"きゅうけいじょ"}
,
{"id":"517","eword":"hokongoin","jword":"法金剛院","hiragana":"ほうこんごういん"}
,
{"id":"518","eword":"sentogosho","jword":"仙洞御所","hiragana":"せんとうごしょ"}
,
{"id":"519","eword":"yoshiminedera","jword":"善峯寺","hiragana":"よしみねで"}
,
{"id":"520","eword":"kansai-airport","jword":"関空","hiragana":"かんくう"}
,
{"id":"521","eword":"ishiyamadera","jword":"石山寺","hiragana":"いしやまでら"}
,
{"id":"522","eword":"moneychange","jword":"両替所","hiragana":"りょうがえじょ"}
,
{"id":"523","eword":"bishamondo","jword":"毘沙門堂","hiragana":"びしゃもんどう"}
,
{"id":"524","eword":"nijo-castle","jword":"二条城","hiragana":"にじょうじょう"}
,
{"id":"525","eword":"kintetsuline","jword":"近鉄線","hiragana":"きんてつせん"}
,
{"id":"526","eword":"karasumaline","jword":"烏丸線","hiragana":"からすません"}
,
{"id":"527","eword":"commuter-pass","jword":"定期券","hiragana":"ていきけん"}
,
{"id":"528","eword":"coupon-ticket","jword":"定期券","hiragana":"ていきけん"}
,
{"id":"529","eword":"kuina-bridge","jword":"くいな橋","hiragana":"くいなばし"}
,
{"id":"530","eword":"highway-bus","jword":"高速バス","hiragana":"こうそくばす"}
,
{"id":"531","eword":"post-office","jword":"郵便局","hiragana":"ゆうびんきょく"}
,
{"id":"532","eword":"bullet-train","jword":"新幹線","hiragana":"しんかんせん"}
,
{"id":"533","eword":"subway-station","jword":"地下鉄","hiragana":"ちかてつ"}
,
{"id":"534","eword":"car-rental","jword":"レンタカー","hiragana":"れんたかー"}
,
{"id":"535","eword":"chuoguchi","jword":"中央口","hiragana":"ちゅうおうぐち"}
,
{"id":"536","eword":"shinkaisoku","jword":"新幹線","hiragana":"しんかんせん"}
,
{"id":"537","eword":"hozugawa","jword":"保津川下り","hiragana":"ほずがわくだり"}
,
{"id":"538","eword":"elevator","jword":"エレベーター","hiragana":"えれべーたー"}
,
{"id":"539","eword":"biwako-line","jword":"琵琶湖線","hiragana":"びわこせん"}
,
{"id":"540","eword":"kansai-airport","jword":"関空","hiragana":"かんくう"}
,
{"id":"541","eword":"postoffice","jword":"郵便局","hiragana":"ゆうびんきょく"}
,
{"id":"542","eword":"kyoto-food","jword":"京料理","hiragana":"きょうりょうり"}
,
{"id":"543","eword":"gionshijo","jword":"祇園四条","hiragana":"ぎおんしじょう"}
,
{"id":"544","eword":"ota-jinja","jword":"太田神社","hiragana":"おおたじんじゃ"}
,
{"id":"545","eword":"otokunitera","jword":"乙訓寺","hiragana":"おとくにてら"}
,
{"id":"546","eword":"chushojima","jword":"中書島","hiragana":"ちゅうしょじま"}
,
{"id":"547","eword":"mimuroto-ji","jword":"三室戸寺","hiragana":"みむろとじ"}
,
{"id":"548","eword":"aeonmall","jword":"イオンモール","hiragana":"いおんもーる"}
,
{"id":"549","eword":"marutamachi","jword":"丸太町","hiragana":"まるたまち"}
,
{"id":"550","eword":"bento-shop","jword":"お弁当屋","hiragana":"おべんとうや"}
,
{"id":"551","eword":"kansaiairport","jword":"関空","hiragana":"かんくう"}
,
{"id":"552","eword":"metro-station","jword":"地下鉄","hiragana":"ちかてつ"}
,
{"id":"553","eword":"kaju-ji-temple","jword":"勧修寺","hiragana":"勧修寺"}
,
{"id":"554","eword":"kuramaguchi","jword":"鞍馬口","hiragana":"くらまぐち"}
,
{"id":"555","eword":"restaurant","jword":"レストラン","hiragana":"れすとらん"}
,
{"id":"556","eword":"bullettrain","jword":"新幹線","hiragana":"しんかんせん"}
,
{"id":"557","eword":"matsugasaki","jword":"松ヶ崎","hiragana":"まつがさき"}
,
{"id":"558","eword":"firework","jword":"花火大会","hiragana":"はなびたいかい"}
,
{"id":"559","eword":"shoren-in","jword":"青蓮院","hiragana":"しょうれんいん"}
,
{"id":"560","eword":"chishakuin","jword":"智積院","hiragana":"ちしゃくいん"}
,
{"id":"561","eword":"mimurotoji","jword":"三室戸寺","hiragana":"みむろとじ"}
,
{"id":"562","eword":"ruriko-in","jword":"瑠璃光院","hiragana":"るりこういん"}
,
{"id":"563","eword":"shinkansen","jword":"新幹線","hiragana":"しんかんせん"}
,
{"id":"564","eword":"otajinja","jword":"太田神社","hiragana":"おおたじんじゃ"}
,
{"id":"565","eword":"nenbutsu-ji","jword":"念仏寺","hiragana":"ねんぶつじ"}
,
{"id":"566","eword":"kuinabashi","jword":"くいな橋","hiragana":"くいなばし"}
,
{"id":"567","eword":"clock-tower","jword":"時計台","hiragana":"とけいだい"}
,
{"id":"568","eword":"generalstore","jword":"雑貨屋","hiragana":"ざっかや"}
,
{"id":"569","eword":"west-entrance","jword":"西口","hiragana":"にしぐち"}
,
{"id":"570","eword":"keikyu-in","jword":"桂宮院","hiragana":"けいきゅういん"}
,
{"id":"571","eword":"japanese-food","jword":"和食","hiragana":"わしょく"}
,
{"id":"572","eword":"kyoto-line","jword":"京都線","hiragana":"きょうとせん"}
,
{"id":"573","eword":"biwakoline","jword":"琵琶湖線","hiragana":"びわこせん"}
,
{"id":"574","eword":"katsura-gawa","jword":"桂川","hiragana":"かつらがわ"}
,
{"id":"575","eword":"myoshin-ji","jword":"妙心寺","hiragana":"みょうしんじ"}
,
{"id":"576","eword":"ekiben-shop","jword":"駅弁屋","hiragana":"えきべんや"}
,
{"id":"577","eword":"western-food","jword":"洋食","hiragana":"ようしょく"}
,
{"id":"578","eword":"kawaramachi","jword":"河原町","hiragana":"かわらまち"}
,
{"id":"579","eword":"tanbaguchi","jword":"丹波口","hiragana":"たんばぐち"}
,
{"id":"580","eword":"shokoku-ji","jword":"相国寺","hiragana":"しょうこくじ"}
,
{"id":"581","eword":"coffee-shop","jword":"喫茶店","hiragana":"きっさてん"}
,
{"id":"582","eword":"enryaku-ji","jword":"延暦寺","hiragana":"えんりゃくじ"}
,
{"id":"583","eword":"shin-osaka","jword":"新大阪","hiragana":"しんおおさか"}
,
{"id":"584","eword":"shinnyodo","jword":"真如堂","hiragana":"しんにょうどう"}
,
{"id":"585","eword":"daisen-in","jword":"大仙院","hiragana":"だいせんいん"}
,
{"id":"586","eword":"jonan-gu","jword":"城南宮","hiragana":"じょうなんぐう"}
,
{"id":"587","eword":"shinosaka","jword":"新大阪","hiragana":"しんおおさか"}
,
{"id":"588","eword":"imadegawa","jword":"今出川","hiragana":"いまでがわ"}
,
{"id":"589","eword":"enryakuji","jword":"延暦寺","hiragana":"えんりゃくじ"}
,
{"id":"590","eword":"sennyu-ji","jword":"泉涌寺","hiragana":"せんにゅうじ"}
,
{"id":"591","eword":"daikaku-ji","jword":"大覚寺","hiragana":"だいかくじ"}
,
{"id":"592","eword":"shokokuji","jword":"相国寺","hiragana":"しょうこくじ"}
,
{"id":"593","eword":"kyotoline","jword":"京都線","hiragana":"きょうとせん"}
,
{"id":"594","eword":"rurikoin","jword":"瑠璃光院","hiragana":"るりこういん"}
,
{"id":"595","eword":"ginkaku-ji","jword":"銀閣寺","hiragana":"ぎんかくじ"}
,
{"id":"596","eword":"myoshinji","jword":"妙心寺","hiragana":"みょうしんじ"}
,
{"id":"597","eword":"rentacar","jword":"レンタカー","hiragana":"れんたかー"}
,
{"id":"598","eword":"kinkaku-ji","jword":"金閣寺","hiragana":"きんかくじ"}
,
{"id":"599","eword":"westernfood","jword":"洋食","hiragana":"ようしょく"}
,
{"id":"600","eword":"coffeeshop","jword":"喫茶店","hiragana":"きっさてん"}
,
{"id":"601","eword":"manpuku-ji","jword":"萬福寺","hiragana":"まんぷくじ"}
,
{"id":"602","eword":"manshu-in","jword":"曼殊院","hiragana":"まんしゅいん"}
,
{"id":"603","eword":"gift-shop","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"604","eword":"chinese-food","jword":"中華","hiragana":"ちゅうか"}
,
{"id":"605","eword":"japanesefood","jword":"和食","hiragana":"わしょく"}
,
{"id":"606","eword":"westentrance","jword":"西口","hiragana":"にしぐち"}
,
{"id":"607","eword":"rokkakudo","jword":"六角堂","hiragana":"ろっかくどう"}
,
{"id":"608","eword":"ramen-shop","jword":"ラーメン","hiragana":"らーめん"}
,
{"id":"609","eword":"katsuragawa","jword":"桂川","hiragana":"かつらがわ"}
,
{"id":"610","eword":"shorenin","jword":"青蓮院","hiragana":"しょうれんいん"}
,
{"id":"611","eword":"tenryu-ji","jword":"天龍寺","hiragana":"てんりゅうじ"}
,
{"id":"612","eword":"kosei-line","jword":"湖西線","hiragana":"こさいせん"}
,
{"id":"613","eword":"shoseien","jword":"渉成園","hiragana":"しょうせいえん"}
,
{"id":"614","eword":"keikyuin","jword":"桂宮院","hiragana":"けいきゅういん"}
,
{"id":"615","eword":"nenbutsuji","jword":"念仏寺","hiragana":"ねんぶつじ"}
,
{"id":"616","eword":"daitoku-ji","jword":"大徳寺","hiragana":"だいとくじ"}
,
{"id":"617","eword":"seiryo-ji","jword":"清涼寺","hiragana":"せいりょうじ"}
,
{"id":"618","eword":"higashiyama","jword":"東山","hiragana":"ひがしやま"}
,
{"id":"619","eword":"ryotokuji","jword":"了徳寺","hiragana":"りょうとくじ"}
,
{"id":"620","eword":"","jword":"undefined","hiragana":"undefined"},
{"id":"621","eword":"crepe-shop","jword":"クレープ","hiragana":"くれーぷ"}
,
{"id":"622","eword":"ryogaejo","jword":"両替所","hiragana":"りょうがえじょ"}
,
{"id":"623","eword":"nembutsuji","jword":"念仏寺","hiragana":"ねんぶつじ"}
,
{"id":"624","eword":"josho-ji","jword":"常照寺","hiragana":"じょうしょうじ"}
,
{"id":"625","eword":"zuishinin","jword":"隨心院","hiragana":"ずいしんいん"}
,
{"id":"626","eword":"wait-room","jword":"待合室","hiragana":"まちあいしつ"}
,
{"id":"627","eword":"higasiyama","jword":"東山","hiragana":"ひがしやま"}
,
{"id":"628","eword":"daikakuji","jword":"大覚寺","hiragana":"だいかくじ"}
,
{"id":"629","eword":"sanzenin","jword":"三千院","hiragana":"さんぜんいん"}
,
{"id":"630","eword":"ryoan-ji","jword":"龍安寺","hiragana":"りょうあんじ"}
,
{"id":"631","eword":"jonangu","jword":"城南宮","hiragana":"じょうなんぐう"}
,
{"id":"632","eword":"genko-ji","jword":"源光庵","hiragana":"げんこうあん"}
,
{"id":"633","eword":"kintetsu","jword":"近鉄線","hiragana":"きんてつせん"}
,
{"id":"634","eword":"manpukuji","jword":"萬福寺","hiragana":"まんぷくじ"}
,
{"id":"635","eword":"nanzen-ji","jword":"南禅寺","hiragana":"なんぜんじ"}
,
{"id":"636","eword":"daisenin","jword":"大仙院","hiragana":"だいせんいん"}
,
{"id":"637","eword":"seiryoji","jword":"清涼寺","hiragana":"せいりょうじ"}
,
{"id":"638","eword":"koseiline","jword":"湖西線","hiragana":"こさいせん"}
,
{"id":"639","eword":"tenryuji","jword":"天龍寺","hiragana":"てんりゅうじ"}
,
{"id":"640","eword":"shutter","jword":"シャッター","hiragana":"しゃったー"}
,
{"id":"641","eword":"komyo-ji","jword":"光明寺","hiragana":"こうみょうじ"}
,
{"id":"642","eword":"niijojo","jword":"二条城","hiragana":"にじょうじょう"}
,
{"id":"643","eword":"taizo-in","jword":"退蔵院","hiragana":"たいぞういん"}
,
{"id":"644","eword":"hokyo-ji","jword":"法鏡寺","hiragana":"ほうきょうじ"}
,
{"id":"645","eword":"koryu-ji","jword":"広隆寺","hiragana":"こうりゅうじ"}
,
{"id":"646","eword":"waitroom","jword":"待合室","hiragana":"まちあいしつ"}
,
{"id":"647","eword":"ginkakuji","jword":"銀閣寺","hiragana":"ぎんかくじ"}
,
{"id":"648","eword":"daisen-ji","jword":"大仙寺","hiragana":"だいせんじ"}
,
{"id":"649","eword":"zenrin-ji","jword":"禅林寺","hiragana":"ぜんりんじ"}
,
{"id":"650","eword":"joshoji","jword":"常照寺","hiragana":"じょうしょうじ"}
,
{"id":"651","eword":"kennin-ji","jword":"建仁寺","hiragana":"けんにんじ"}
,
{"id":"652","eword":"byodoin","jword":"平等院","hiragana":"びょうどういん"}
,
{"id":"653","eword":"koetsu-ji","jword":"光悦寺","hiragana":"こうえつじ"}
,
{"id":"654","eword":"ramenshop","jword":"ラーメン","hiragana":"らーめん"}
,
{"id":"655","eword":"arashiyama","jword":"嵐山","hiragana":"あらしやま"}
,
{"id":"656","eword":"restroom","jword":"お手洗い","hiragana":"おてあらい"}
,
{"id":"657","eword":"yatsuhashi","jword":"八ツ橋","hiragana":"やつはし"}
,
{"id":"658","eword":"daitokuji","jword":"大徳寺","hiragana":"だいとくじ"}
,
{"id":"659","eword":"sennyuji","jword":"泉涌寺","hiragana":"せんにゅうじ"}
,
{"id":"660","eword":"kinkakuji","jword":"金閣寺","hiragana":"きんかくじ"}
,
{"id":"661","eword":"manshuin","jword":"曼殊院","hiragana":"まんしゅいん"}
,
{"id":"662","eword":"tofuku-ji","jword":"東福寺","hiragana":"とうふくじ"}
,
{"id":"663","eword":"pontocho","jword":"先斗町","hiragana":"ぽんとちょう"}
,
{"id":"664","eword":"hashidate","jword":"はしだて","hiragana":"はしだて"}
,
{"id":"665","eword":"to-ji-temple","jword":"東寺","hiragana":"とうじ"}
,
{"id":"666","eword":"imadegawa","jword":"今出川","hiragana":"いまでがわ"}
,
{"id":"667","eword":"giftshop","jword":"お土産屋","hiragana":"おみやげや"}
,
{"id":"668","eword":"yamashina","jword":"山科","hiragana":"やましな"}
,
{"id":"669","eword":"tofukuji","jword":"東福寺","hiragana":"とうふくじ"}
,
{"id":"670","eword":"mibu-dera","jword":"壬生寺","hiragana":"みぶでら"}
,
{"id":"671","eword":"saiho-ji","jword":"西芳寺","hiragana":"さいほうじ"}
,
{"id":"672","eword":"hiiragiya","jword":"柊家","hiragana":"ひいらぎや"}
,
{"id":"673","eword":"bentoya","jword":"お弁当屋","hiragana":"おべんとう"}
,
{"id":"674","eword":"daisenji","jword":"大仙寺","hiragana":"だいせんじ"}
,
{"id":"675","eword":"kodai-ji","jword":"高台寺","hiragana":"こうだいじ"}
,
{"id":"676","eword":"ekibenya","jword":"駅弁屋","hiragana":"えきべんや"}
,
{"id":"677","eword":"nijojo","jword":"二条城","hiragana":"にじょうじょう"}
,
{"id":"678","eword":"horin-ji","jword":"法輪寺","hiragana":"ほうりんじ"}
,
{"id":"679","eword":"honen-in","jword":"法然院","hiragana":"ほうねいん"}
,
{"id":"680","eword":"hokyoji","jword":"法鏡寺","hiragana":"ほうきょうじ"}
,
{"id":"681","eword":"shisendo","jword":"詩仙堂","hiragana":"しせんどう"}
,
{"id":"682","eword":"kinzo-ji","jword":"金蔵寺","hiragana":"こんぞうじ"}
,
{"id":"683","eword":"kuroshio","jword":"くろしお","hiragana":"くろしお"}
,
{"id":"684","eword":"genkoan","jword":"源光庵","hiragana":"げんこうあん"}
,
{"id":"685","eword":"rokujizo","jword":"六地蔵","hiragana":"ろくじぞう"}
,
{"id":"686","eword":"higashino","jword":"東野","hiragana":"ひがしの"}
,
{"id":"687","eword":"nara-line","jword":"奈良線","hiragana":"ならせん"}
,
{"id":"688","eword":"ryuanji","jword":"龍安寺","hiragana":"りゅうあんじ"}
,
{"id":"689","eword":"avanti","jword":"アバンティ","hiragana":"あばんてぃ"}
,
{"id":"690","eword":"taishido","jword":"太子堂","hiragana":"たいしどう"}
,
{"id":"691","eword":"kenninji","jword":"建仁寺","hiragana":"けんにんじ"}
,
{"id":"692","eword":"ryoanji","jword":"龍安寺","hiragana":"りょうあんじ"}
,
{"id":"693","eword":"kenniji","jword":"建仁寺","hiragana":"けんんにんじ"}
,
{"id":"694","eword":"hokai-ji","jword":"法界寺","hiragana":"ほうかいじ"}
,
{"id":"695","eword":"nison-in","jword":"二尊院","hiragana":"にそんいん"}
,
{"id":"696","eword":"honno-ji","jword":"本能寺","hiragana":"ほんのうじ"}
,
{"id":"697","eword":"shoji-ji","jword":"勝持寺","hiragana":"しょうじじ"}
,
{"id":"698","eword":"zenrinji","jword":"禅林寺","hiragana":"ぜんりんじ"}
,
{"id":"699","eword":"jisso-in","jword":"実相院","hiragana":"じっそうじ"}
,
{"id":"700","eword":"eikando","jword":"永観堂","hiragana":"えいかんどう"}
,
{"id":"701","eword":"shogoin","jword":"聖護院","hiragana":"しょうごいん"}
,
{"id":"702","eword":"koetsuji","jword":"光悦寺","hiragana":"こうえつじ"}
,
{"id":"703","eword":"koryuji","jword":"広隆寺","hiragana":"こうりゅうじ"}
,
{"id":"704","eword":"taizoin","jword":"退蔵院","hiragana":"たいぞういん"}
,
{"id":"705","eword":"komyoji","jword":"光明寺","hiragana":"こうみょうじ"}
,
{"id":"706","eword":"nanzenji","jword":"南禅寺","hiragana":"なんぜんじ"}
,
{"id":"707","eword":"kitaoji","jword":"北大路","hiragana":"きたおおじ"}
,
{"id":"708","eword":"amagasaki","jword":"尼崎","hiragana":"あまがさき"}
,
{"id":"709","eword":"pharmacy","jword":"薬局","hiragana":"やっきょく"}
,
{"id":"710","eword":"hoon-ji","jword":"報恩寺","hiragana":"ほうおんじ"}
,
{"id":"711","eword":"genkoji","jword":"源光寺","hiragana":"げんこうじ"}
,
{"id":"712","eword":"tennoji","jword":"天王寺","hiragana":"てんのうじ"}
,
{"id":"713","eword":"hokaiji","jword":"法界寺","hiragana":"ほうかいじ"}
,
{"id":"714","eword":"rozan-ji","jword":"廬山寺","hiragana":"ろざんじ"}
,
{"id":"715","eword":"konzoji","jword":"金蔵寺","hiragana":"こんぞうじ"}
,
{"id":"716","eword":"koyasan","jword":"高野山","hiragana":"こうやさん"}
,
{"id":"717","eword":"jissoin","jword":"実相院","hiragana":"じっそうじ"}
,
{"id":"718","eword":"takatsuki","jword":"高槻","hiragana":"たかつき"}
,
{"id":"719","eword":"nagitsuji","jword":"椥辻","hiragana":"なぎつじ"}
,
{"id":"720","eword":"mibudera","jword":"壬生寺","hiragana":"みぶでら"}
,
{"id":"721","eword":"chion-in","jword":"知恩院","hiragana":"ちおいん"}
,
{"id":"722","eword":"kodaiji","jword":"高台寺","hiragana":"こうだいじ"}
,
{"id":"723","eword":"misasagi","jword":"御陵","hiragana":"みささぎ"}
,
{"id":"724","eword":"yamashina","jword":"山科","hiragana":"やましな"}
,
{"id":"725","eword":"komeiji","jword":"光明寺","hiragana":"こうめいじ"}
,
{"id":"726","eword":"mii-dera","jword":"三井寺","hiragana":"みいでら"}
,
{"id":"727","eword":"hanazono","jword":"花園","hiragana":"はなぞの"}
,
{"id":"728","eword":"naraline","jword":"奈良線","hiragana":"ならせん"}
,
{"id":"729","eword":"tearai","jword":"お手洗い","hiragana":"おてあらい"}
,
{"id":"730","eword":"jingo-ji","jword":"神護寺","hiragana":"じんごじ"}
,
{"id":"731","eword":"toilet","jword":"お手洗い","hiragana":"おてあらい"}
,
{"id":"732","eword":"tashido","jword":"太子堂","hiragana":"たいしどう"}
,
{"id":"733","eword":"horinji","jword":"法輪寺","hiragana":"ほうりんじ"}
,
{"id":"734","eword":"honenin","jword":"法然院","hiragana":"ほうねいん"}
,
{"id":"735","eword":"saihoji","jword":"西芳寺","hiragana":"さいほうじ"}
,
{"id":"736","eword":"nisonin","jword":"二尊院","hiragana":"にそんいん"}
,
{"id":"737","eword":"enko-ji","jword":"圓光寺","hiragana":"えんこうじ"}
,
{"id":"738","eword":"ninna-ji","jword":"仁和寺","hiragana":"にんなじ"}
,
{"id":"739","eword":"hiroshima","jword":"広島","hiragana":"ひろしま"}
,
{"id":"740","eword":"hoko-ji","jword":"方広寺","hiragana":"ほうこうじ"}
,
{"id":"741","eword":"toji-in","jword":"等持院","hiragana":"とうじいん"}
,
{"id":"742","eword":"honnoji","jword":"本能寺","hiragana":"ほんのうじ"}
,
{"id":"743","eword":"souvenir","jword":"お土産","hiragana":"おみやげ"}
,
{"id":"744","eword":"uniqlo","jword":"ユニクロ","hiragana":"ゆにくろ"}
,
{"id":"745","eword":"gion-ji","jword":"祇園寺","hiragana":"ぎおんじ"}
,
{"id":"746","eword":"enkoji","jword":"圓光寺","hiragana":"えんこうじ"}
,
{"id":"747","eword":"crepes","jword":"クレープ","hiragana":"くれーぷ"}
,
{"id":"748","eword":"kitayama","jword":"北山","hiragana":"きたやま"}
,
{"id":"749","eword":"kanazawa","jword":"金沢","hiragana":"かなざわ"}
,
{"id":"750","eword":"bento","jword":"お弁当屋","hiragana":"おべんとう"}
,
{"id":"751","eword":"miidera","jword":"三井寺","hiragana":"みいでら"}
,
{"id":"752","eword":"sakai-city","jword":"堺","hiragana":"さかい"}
,
{"id":"753","eword":"hoonji","jword":"報恩寺","hiragana":"ほうおんじ"}
,
{"id":"754","eword":"tojiin","jword":"等持院","hiragana":"とうじいん"}
,
{"id":"755","eword":"lawson","jword":"ローソン","hiragana":"ろーそん"}
,
{"id":"756","eword":"ekibiru","jword":"駅ビル","hiragana":"えきびる"}
,
{"id":"757","eword":"yokohama","jword":"横浜","hiragana":"よこはま"}
,
{"id":"758","eword":"daigoji","jword":"醍醐寺","hiragana":"だいごじ"}
,
{"id":"759","eword":"inkuji","jword":"印空寺","hiragana":"いんくうじ"}
,
{"id":"760","eword":"kegonji","jword":"華厳寺","hiragana":"けごんじ"}
,
{"id":"761","eword":"chionin","jword":"知恩院","hiragana":"ちおいん"}
,
{"id":"762","eword":"hokoji","jword":"方広寺","hiragana":"ほうこうじ"}
,
{"id":"763","eword":"rozanji","jword":"廬山寺","hiragana":"ろざんじ"}
,
{"id":"764","eword":"city-bus","jword":"市バス","hiragana":"しばす"}
,
{"id":"765","eword":"jingoji","jword":"神護寺","hiragana":"じんごじ"}
,
{"id":"766","eword":"shojiji","jword":"勝持寺","hiragana":"しょうじ"}
,
{"id":"767","eword":"kamakura","jword":"鎌倉","hiragana":"かまくら"}
,
{"id":"768","eword":"bookstore","jword":"本屋","hiragana":"ほんや"}
,
{"id":"769","eword":"ninnaji","jword":"仁和寺","hiragana":"にんなじ"}
,
{"id":"770","eword":"ekiben","jword":"駅弁屋","hiragana":"えきべん"}
,
{"id":"771","eword":"isetan","jword":"伊勢丹","hiragana":"いせたん"}
,
{"id":"772","eword":"fushimi","jword":"伏見","hiragana":"ふしみ"}
,
{"id":"773","eword":"sweet","jword":"スイーツ","hiragana":"すいーつ"}
,
{"id":"774","eword":"ramen","jword":"ラーメン","hiragana":"らーめん"}
,
{"id":"775","eword":"jujo","jword":"十条","hiragana":"じゅうじょう"}
,
{"id":"776","eword":"sapporo","jword":"札幌","hiragana":"さっぽろ"}
,
{"id":"777","eword":"uzumasa","jword":"太秦","hiragana":"うずまさ"}
,
{"id":"778","eword":"gionji","jword":"祇園寺","hiragana":"ぎおんじ"}
,
{"id":"779","eword":"satin","jword":"喫茶店","hiragana":"きっさてん"}
,
{"id":"780","eword":"raman","jword":"ラーメン","hiragana":"らーめん"}
,
{"id":"781","eword":"fujieda","jword":"藤枝","hiragana":"ふじえだ"}
,
{"id":"782","eword":"tionin","jword":"知恩院","hiragana":"ちおいん"}
,
{"id":"783","eword":"suica","jword":"SUICA","hiragana":"すいか"}
,
{"id":"784","eword":"icoca","jword":"ICOCA","hiragana":"いこか"}
,
{"id":"785","eword":"subway","jword":"地下鉄","hiragana":"ちかてつ"}
,
{"id":"786","eword":"crepe","jword":"クレープ","hiragana":"くれーぷ"}
,
{"id":"787","eword":"takeda","jword":"竹田","hiragana":"たけだ"}
,
{"id":"788","eword":"tokyo","jword":"東京","hiragana":"とうきょう"}
,
{"id":"789","eword":"kajuji","jword":"勧修寺","hiragana":"勧修寺"}
,
{"id":"790","eword":"kanku","jword":"関空","hiragana":"かんくう"}
,
{"id":"791","eword":"nagoya","jword":"名古屋","hiragana":"なごや"}
,
{"id":"792","eword":"taxi","jword":"タクシー","hiragana":"たくしー"}
,
{"id":"793","eword":"metro","jword":"地下鉄","hiragana":"ちかてつ"}
,
{"id":"794","eword":"haruka","jword":"はるか","hiragana":"はるか"}
,
{"id":"795","eword":"sagano","jword":"嵯峨野","hiragana":"さがの"}
,
{"id":"796","eword":"tsuruga","jword":"敦賀","hiragana":"つるが"}
,
{"id":"797","eword":"ishida","jword":"石田","hiragana":"いしだ"}
,
{"id":"798","eword":"bus-stop","jword":"バス","hiragana":"ばす"}
,
{"id":"799","eword":"market","jword":"市場","hiragana":"いちば"}
,
{"id":"800","eword":"kujo","jword":"九条","hiragana":"くじょう"}
,
{"id":"801","eword":"obaku","jword":"黄檗","hiragana":"おうばく"}
,
{"id":"802","eword":"ashiya","jword":"芦屋","hiragana":"あしや"}
,
{"id":"803","eword":"osaka","jword":"大阪","hiragana":"おおさか"}
,
{"id":"804","eword":"nijo","jword":"二条","hiragana":"にじょう"}
,
{"id":"805","eword":"hakata","jword":"博多","hiragana":"はかた"}
,
{"id":"806","eword":"shijo","jword":"四条","hiragana":"しじょう"}
,
{"id":"807","eword":"matsue","jword":"松江","hiragana":"まつえ"}
,
{"id":"808","eword":"atm","jword":"ATM","hiragana":"えいてえむ"}
,
{"id":"809","eword":"toyama","jword":"富山","hiragana":"とやま"}
,
{"id":"810","eword":"tube","jword":"地下鉄","hiragana":"ちかてつ"}
,
{"id":"811","eword":"kyoto","jword":"京都","hiragana":"きょうと"}
,
{"id":"812","eword":"daigo","jword":"醍醐","hiragana":"だいご"}
,
{"id":"813","eword":"to-ji","jword":"東寺","hiragana":"とうじ"}
,
{"id":"814","eword":"inari","jword":"稲荷","hiragana":"いなり"}
,
{"id":"815","eword":"keage","jword":"蹴上","hiragana":"けあげ"}
,
{"id":"816","eword":"station","jword":"駅","hiragana":"えき"}
,
{"id":"817","eword":"cafe","jword":"喫茶店","hiragana":"かふぇ"}
,
{"id":"818","eword":"umeda","jword":"梅田","hiragana":"うめだ"}
,
{"id":"819","eword":"café","jword":"喫茶店","hiragana":"かふぇ"}
,
{"id":"820","eword":"sabae","jword":"鯖江","hiragana":"さばえ"}
,
{"id":"821","eword":"gojo","jword":"五条","hiragana":"ごじょう"}
,
{"id":"822","eword":"kobe","jword":"神戸","hiragana":"こうべ"}
,
{"id":"823","eword":"sakai","jword":"堺","hiragana":"さかい"}
,
{"id":"824","eword":"gion","jword":"祇園","hiragana":"ぎおん"}
,
{"id":"825","eword":"tsuge","jword":"柘植","hiragana":"つげ"}
,
{"id":"826","eword":"toji","jword":"東寺","hiragana":"とうじ"}
,
{"id":"827","eword":"hida","jword":"ひだ","hiragana":"ひだ"}
,
{"id":"828","eword":"nara","jword":"奈良","hiragana":"なら"}
,
{"id":"829","eword":"ono","jword":"小野","hiragana":"おの"}
,
{"id":"830","eword":"uji","jword":"宇治","hiragana":"うじ"}
,
{"id":"831","eword":"ise","jword":"伊勢","hiragana":"いせ"}
,
{"id":"832","eword":"bus","jword":"バス","hiragana":"ばす"}

]
)}}
