module.exports = {make: function (){return( 
[
{"id":"1","jword":"コトチカ","eword":"Kotocihka"}
,
{"id":"2","jword":"昼得","eword":"Hirutoku"}
,
{"id":"3","jword":"駅ビル","eword":"StationBuilding"}
,
{"id":"4","jword":"551蓬莱","eword":"Gogoichihorai"}
,
{"id":"5","jword":"雑貨屋","eword":"GeneralStore"}
,
{"id":"6","jword":"スタバ","eword":"STARBUCKS"}
,
{"id":"7","jword":"スターバックス","eword":"STARBUCKS"}
,
{"id":"8","jword":"四条河原町","eword":"shijokawaramachi"}
,
{"id":"9","jword":"五条河原町","eword":"gojokawaramachi"}
,
{"id":"10","jword":"お土産屋さん","eword":"Giftshop"}
,
{"id":"11","jword":"大谷納骨堂","eword":"Otaninokotsudo"}
,
{"id":"12","jword":"駅弁","eword":"Ekiben"}
,
{"id":"13","jword":"第二タワーホテル","eword":"Dainitowerhotel"}
,
{"id":"14","jword":"ニッポンレンタカー","eword":"Nipponrentacar"}
,
{"id":"15","jword":"二条城前","eword":"Nijojomae"}
,
{"id":"16","jword":"先着","eword":"Senchaku"}
,
{"id":"17","jword":"はるか","eword":"Haruka"}
,
{"id":"18","jword":"分煙","eword":"Bunen"}
,
{"id":"19","jword":"篠山口","eword":"Sasayamaguchi"}
,
{"id":"20","jword":"みどりの窓口","eword":"Midorinomadoguchi"}
,
{"id":"21","jword":"中央口","eword":"Chuoguchi"}
,
{"id":"22","jword":"専修寺京都別院","eword":"Senshujikyotobekkan"}
,
{"id":"23","jword":"暲子内親王墓","eword":"Akikonaishinonohaka"}
,
{"id":"24","jword":"満月寺浮御堂","eword":"Mangetsuukimido"}
,
{"id":"25","jword":"大原三千院","eword":"Oharasanzenin"}
,
{"id":"26","jword":"聚楽第跡","eword":"Jurakudaiato"}
,
{"id":"27","jword":"大極殿跡","eword":"Taikyokudenato"}
,
{"id":"28","jword":"朱雀門跡","eword":"Suzakumonato"}
,
{"id":"29","jword":"羅城門跡","eword":"Rajomonato"}
,
{"id":"30","jword":"車折神社","eword":"Kurumaorijinja"}
,
{"id":"31","jword":"鈴虫寺","eword":"Suzumushidera"}
,
{"id":"32","jword":"印空寺","eword":"Inkuji"}
,
{"id":"33","jword":"太子堂","eword":"Taishido"}
,
{"id":"34","jword":"三千院","eword":"Sanzenin"}
,
{"id":"35","jword":"三十三間堂","eword":"Sanjusangendo"}
,
{"id":"36","jword":"嵯峨野トロッコ列車","eword":"Saganotrokko"}
,
{"id":"37","jword":"嵯峨野トロッコ","eword":"Saganotrokko"}
,
{"id":"38","jword":"随心院","eword":"Zuishin"}
,
{"id":"39","jword":"地下鉄四条烏丸","eword":"Subwayshijokarasuma"}
,
{"id":"40","jword":"京都市役所前","eword":"Kyotoshiyakushomae"}
,
{"id":"41","jword":"十条","eword":"Jujo"}
,
{"id":"42","jword":"九条","eword":"Kujo"}
,
{"id":"43","jword":"六地蔵","eword":"Rokujizo"}
,
{"id":"44","jword":"御陵","eword":"Misasagi"}
,
{"id":"45","jword":"宇治","eword":"Uji"}
,
{"id":"46","jword":"黄檗","eword":"Obaku"}
,
{"id":"47","jword":"新都ホテル京都","eword":"Shinmiyakohotel"}
,
{"id":"48","jword":"ホテル近鉄京都駅","eword":"Hotelkintetsukyotostation"}
,
{"id":"49","jword":"エルイン京都","eword":"Elinnkyoto"}
,
{"id":"50","jword":"庵町家ステイ","eword":"Iorimachiyastay"}
,
{"id":"51","jword":"アパホテル京都駅前","eword":"Apahotelkyotoekimae"}
,
{"id":"52","jword":"アパホテル京都駅前","eword":"Apahotel"}
,
{"id":"53","jword":"アパヴィラホテル京都駅前","eword":"Apavillahotelkyotoekimae"}
,
{"id":"54","jword":"アパホテル京都駅堀川通り","eword":"Apahotelkyotoekihorikawadori"}
,
{"id":"55","jword":"手回り品きっぷ","eword":"Luggageticket"}
,
{"id":"56","jword":"待ち合わせ場所","eword":"Watingplace"}
,
{"id":"57","jword":"多目的トイレ","eword":"Tamokutekitoire"}
,
{"id":"58","jword":"荷物預かり","eword":"Luggageroom"}
,
{"id":"59","jword":"お弁当屋","eword":"Bentoya"}
,
{"id":"60","jword":"お土産屋","eword":"Giftshop"}
,
{"id":"61","jword":"お手洗い","eword":"Restroom"}
,
{"id":"62","jword":"喫煙場所","eword":"Smokingarea"}
,
{"id":"63","jword":"駅弁屋","eword":"Ekibenya"}
,
{"id":"64","jword":"休憩所","eword":"Restingroom"}
,
{"id":"65","jword":"両替所","eword":"Moneychange"}
,
{"id":"66","jword":"待合室","eword":"Waitroom"}
,
{"id":"67","jword":"レンタカー","eword":"Rentacar"}
,
{"id":"68","jword":"忘れ物センター","eword":"Lostandfound"}
,
{"id":"69","jword":"近鉄乗り場","eword":"Kintetsu Line"}
,
{"id":"70","jword":"近鉄のりば","eword":"Kintetsu Line"}
,
{"id":"71","jword":"近鉄","eword":"Kintetsu Line"}
,
{"id":"72","jword":"新幹線のりば","eword":"Shinkansen"}
,
{"id":"73","jword":"新幹線乗り場","eword":"Shinkansen"}
,
{"id":"74","jword":"新幹線ホーム","eword":"Shinkansen"}
,
{"id":"75","jword":"紅葉","eword":"Koyo"}
,
{"id":"76","jword":"やさか","eword":"Yasaka"}

]
)}}
