module.exports = {make: function (){return( 
[
{"id":"1","word":"hotelkintetsukyotostation"},
{"id":"2","word":"kyoto-century-hotel"},
{"id":"3","word":"hotel-granvia-kyoto"},
{"id":"4","word":"hotel-mystays-kyoto"},
{"id":"5","word":"hotel-keihan-kyoto"},
{"id":"6","word":"kyoto-tower-hotel"},
{"id":"7","word":"hotelgranviakyoto"},
{"id":"8","word":"hotelmystayskyoto"},
{"id":"9","word":"kyotocenturyhotel"},
{"id":"10","word":"hotelkeihankyoto"},
{"id":"11","word":"shinmiyakohotel"},
{"id":"12","word":"kyototowerhotel"},
{"id":"13","word":"hotelkintetsu"},
{"id":"14","word":"hotel-mystays"},
{"id":"15","word":"granvia-kyoto"},
{"id":"16","word":"hankyu-hotel"},
{"id":"17","word":"hotelmystays"},
{"id":"18","word":"granviakyoto"},
{"id":"19","word":"granviakyoto"},
{"id":"20","word":"granviakyoto"},
{"id":"21","word":"hankyuhotel"},
{"id":"22","word":"granvia"},
{"id":"23","word":"granvia"}
]
)}}
